### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetParent' of null

### ISSUE THREAD

**Issue by mort3za** [cferdinandi/smooth-scroll#125]
I am working on this site: 3mcando.com
I just followed instructions and when i click on the links i get this error:

```
Uncaught TypeError: Cannot read property 'offsetParent' of null
```

smooth-scroll.min.js:217

**Comment by davidjbradshaw** [comment]
I'm getting this error, even when using `id`. Here's my HTML.


               <section id="work">
                  <article>
                    <h2>Work</h2><a id="work2"></a>
                  </article>
              </section>

and then I try calling from the console as a test.

    smoothScroll.animateScroll(null,'work');
      Uncaught TypeError: Cannot read property 'offsetParent' of null
    smoothScroll.animateScroll(null,'work2');
      Uncaught TypeError: Cannot read property 'offsetParent' of null

What am I doing wrong?

**Comment by cferdinandi** [comment]
@davidjbradshaw You're not including the leading `#` in the ID:

```javascript
smoothScroll.animateScroll( null, '#work' );
smoothScroll.animateScroll( null, '#work2' );
```

**Comment by cferdinandi** [comment]
@davidjbradshaw Also worth nothing, you can add `id="work2"` directly to the heading element. No need for trailing, empty `<a>` element.

```html
<section id="work">
    <article>
        <h2 id="work2">Work</h2>
    </article>
</section>
```

**Comment by arzavj** [comment]
The same problem seems to occur when I click on
```
<a href="page1#id1">Click Me</a>
````
from page2.

**Comment by cferdinandi** [comment]
That's not a valid href/anchor link.

**Comment by arzavj** [comment]
(Just updated my comment above)

**Comment by cferdinandi** [comment]
@arzavj - Ah yes, you're trying to animate scrolling on another page. Smooth Scroll doesn't support that out-of-the-box, but you can easily add that functionality using the API. 

For anchor links to other pages, DO NOT use the `data-scroll` attribute. Just link as normal. Then, follow the instructions here: https://github.com/cferdinandi/smooth-scroll/issues/54
