### ISSUE TITLE
Bower Install issue

### ISSUE THREAD

**Issue by JayHoltslander** [cferdinandi/smooth-scroll#126]
Installing via Bower using Codekit returns this error:

> Bower failed to install 'smooth-scroll.js'. It returned this error information:
> 
> Code & Message: (null), git://github.com/cferdinandi/smooth-scroll.git#*
> 
> Try these steps to fix general errors:
> 1. Be sure you're connected to the Internet.
> 2. If you are running any blocking/security apps like Little Snitch or Antivirus software, disable those.
> 3. If you have installed Apple's Developer Tools, launch Xcode, accept the license terms and let the installation routine finish.
> 4. Make sure your network or firewall is not blocking the default port for git:// URLs, which is 9418. (Corporate networks do this frequently.) Use the "Tasks" menu to switch Git to use https:// URLs instead.
>    5.Delete the hidden ".cache" directory in your home folder.

None of those suggestions are applicable.

**Comment by trident-ms** [comment]
I solved deleting a very very old version of git that was installed under /usr/local/bin/git
