### ISSUE TITLE
is it possible to scroll a div with overflow scrolling with this, or only the window?

### ISSUE THREAD

**Issue by kellyrmilligan** [cferdinandi/smooth-scroll#139]
wondering if possible to select a div and scroll it with this?

**Comment by cferdinandi** [comment]
The way it's presently written, only the Window. I can see the use case of an overflow-scrolling div, though.

However, it would require me to rewrite some code.

**Comment by ronzeidman** [comment]
I've made a quick & dirty implementation to this feature, you can see in my fork https://github.com/ronzeidman/smooth-scroll
in short you can initialize with these three additional settings:
```js
//this is an example for use with material design lite
smoothScroll.init({
    speed: 1000,
    easing: 'easeOutQuint',
    selectorHeader: '.mdl-layout__header',
    bodyElement: document.getElementsByClassName('page-content')[0],
    documentElement: document.getElementsByClassName('mdl-layout__content')[0],
    rootElement: document.getElementsByClassName('mdl-layout__content')[0]
});
```
and that's it
my change was just to change all body/root/documentElement elements with their corresponding setting value and add three functions so that the root can be either a window or an element:

```js
/**
	 * Gets the height of the root element
	 * @private
	 * @returns {Number}
	 */
	var getRootHeight = function () {
		return typeof settings.rootElement.clientHeight !== 'undefined' ?
			settings.rootElement.clientHeight:
			settings.rootElement.innerHeight;
	};

	/**
	 * Scrolls to top
	 * @private
	 * @param {Number} top
	 */
	var scrollTop = function ( top) {
		if (settings.rootElement.scrollTo) {
			settings.rootElement.scrollTo(0, top);
		}
		settings.rootElement.scrollTop = top;
	};

	/**
	 * Returns the current scrollbar position
	 * @private
	 * @returns {Number}
	 */
	var getRootTop = function () {
		return settings.rootElement.pageYOffset || settings.rootElement.scrollTop;
	};
```
I might have missed some usecases but it works great for me so if you want you can merge (probably give better names to the elements...)

**Comment by cferdinandi** [comment]
I actually think this is something I could roll into Smooth Scroll proper.

**Comment by Grandclosing** [comment]
Hey @cferdinandi - is the ability to scroll inside of a div integrated already into the library? It seems that it works for me, but I can't figure out how to get the animation to work - the call to animateScroll() snaps the view to the node I want but doesn't animate up there...

**Comment by cferdinandi** [comment]
Today, scrolling is only supported the whole documented.

**Comment by Grandclosing** [comment]
Ok no problem - somehow it still works in my div though without the animation, I'll take that for now! Thanks for the wonderful library.

**Comment by cferdinandi** [comment]
@Grandclosing Do you have a link I could take a look at? I'd love to see a specific example of what you're doing, so I can adjust the script to work for your use case.

**Comment by yciabaud** [comment]
I am interested in this too to add smooth scrolling to my inner popups but I would need a selector for my container since I have several popups in my page.

The header needs to be ignored if it is not in the container, do you think it is possible?

Do you want me to push a PR in this way?

**Comment by cferdinandi** [comment]
This has turned out to be a lot more complicated than initially thought, and as it's outside the scope of this plugins core objective, I'm going to close this one out.
