### ISSUE TITLE
data-scroll-header doesn't work as expected

### ISSUE THREAD

**Issue by hiulit** [cferdinandi/smooth-scroll#141]
Me again :P 

I'm using `smoothScroll` with `Gumshoe` like this:

```
smoothScroll.init({
	offset: 40,
	updateURL: false
});

gumshoe.init({
	offset: 41
});
```

And in my fixed header I put both `data-gumshoe-header` and `data-scroll-header`.

Am I doing something wrong?

The offset seems to work just fine. What it doesn't seem to work is the `data-scroll-header`. It doesn't seem to apply the proper offset from the fixed header's height.

**Comment by cferdinandi** [comment]
@hiulit Do you mind sharing a demo link?

**Comment by hiulit** [comment]
Oh, shoot! I'm sorry, I'm not using that header anymore... 
I guess it was something I did wrong if no one has complained about it
