### ISSUE TITLE
Support for :target styling

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/smooth-scroll#142]
* https://twitter.com/DavidDarnes/status/560859653538848768
* https://developer.mozilla.org/en-US/docs/Web/CSS/:target

**Comment by daviddarnes** [comment]
Created a quick CodePen to reproduce the bug http://codepen.io/daviddarnes/pen/ogeMeK

**Comment by cferdinandi** [comment]
After doing some research, it appears this a longstanding bug with `history.pushState` in both WebKit and Mozilla browsers. Simply put, browsers do not reevaluate CSS rules on `pushState`.

* https://bugs.webkit.org/show_bug.cgi?id=83490
* https://code.google.com/p/chromium/issues/detail?id=89165
* http://lea.verou.me/2011/05/change-url-hash-without-page-jump/#comment-203995404

And the workarounds to this issue prevent history from being updated (meaning the back button won't let you navigate back through your anchor links) and cause a page jump (which defeats the point of the script): http://www.zachleat.com/web/moving-target/

Based on this, I think this has to get filed under wontfix because the solutions are worse than the issue, and it's really something browser-makers need to address.
