### ISSUE TITLE
Highlight active link wehn clicking and/or scrolling 

### ISSUE THREAD

**Issue by fitzliputz** [cferdinandi/smooth-scroll#147]
I really appreciate your fantastic plugin. The only minor thing I'm not getting done is highling the active link when the anchor ist reached. Your suggested solution here: [/cferdinandi/smooth-scroll/issues/51](https://github.com/cferdinandi/smooth-scroll/issues/51) is working brillant, but highlights links only after they were clicked. When scrolling manually of course nothing happens. [This example](http://jsfiddle.net/mekwall/up4nu/) is illustrating it quite well: you click the button or scroll by hand, both actions highlight the links.

Thanks for your help,
Fitz

**Comment by cferdinandi** [comment]
Sounds like you want [Gumshoe](https://github.com/cferdinandi/gumshoe), a complimentary script for Smooth Scroll. [Demo here.](http://cferdinandi.github.io/gumshoe/#eenie)

**Comment by fitzliputz** [comment]
2 thumbs up, Chris – at least! 

Thank you very much and have a nice day
Fitz

**Comment by cferdinandi** [comment]
Happy to help!
