### ISSUE TITLE
Uncaught ReferenceError: headerHeight is not defined

### ISSUE THREAD

**Issue by FreekyMage** [cferdinandi/smooth-scroll#149]
When resizing the window this error keeps popping up, but it doesn't seem to break anything luckily. The error itself is in the eventThrottler function. For now I have encapsulated the code in an if statement that checks if the variable is undefined.
Only tested in the latest chrome version for now.

**Comment by Worstkaes** [comment]
I get the same problem and made a fiddle for this: https://jsfiddle.net/pgup19mc/13/

By resizing the window, we get the error "Uncaught ReferenceError: headerHeight is not defined"

**Comment by cferdinandi** [comment]
fixed in v5.3.4

**Comment by cferdinandi** [comment]
Also, thanks for letting me know about this one.

**Comment by Worstkaes** [comment]
Thanks for fixing so fast. :+1:
