### ISSUE TITLE
recent UMD update breaking webpack, any ideas?

### ISSUE THREAD

**Issue by kellyrmilligan** [cferdinandi/smooth-scroll#152]
i'm getting window as undefined in the feature check. verified that 5.3.3 worked as expected.

**Comment by cferdinandi** [comment]
When I updated, I changed the argument I was passing in from `root` to `window`. Just switched it back to root. Should work now, but could you let me know if that's accurate or not?

**Comment by kellyrmilligan** [comment]
cool, got it working, upgraded gumshoe as well. for anyone else that may land here, with this umd module def, if you're using webpack, you must do this with the imports loader:

{
        test: /smooth-scroll/,
        loader: 'imports?this=>window'
      },
      {
        test: /gumshoe/,
        loader: 'imports?this=>window'
      },

**Comment by cferdinandi** [comment]
Awesome, thanks Kelly!
