### ISSUE TITLE
Bower support and release tags

### ISSUE THREAD

**Issue by stephanebachelier** [cferdinandi/smooth-scroll#155]
Hi,

It would be great to add a bower.json, but most important if you could add tag on this repository, it will help. Last days with the UMD wrapper multiple fixes, smooth scroll was broken.

**Comment by cferdinandi** [comment]
Hi @stephanebachelier - Bower support is in the works. I'll look into tags, as well. Sorry for the issues!

**Comment by lkraav** [comment]
You could just push some git version tags without worrying bower for time being. Just having git tags allows other tools to operate on their own immediately as well.

**Comment by mahnunchik** [comment]
+1

**Comment by mahnunchik** [comment]
The same for https://github.com/cferdinandi/gumshoe

**Comment by cferdinandi** [comment]
Will be adding Git version tags to all of my open source projects. Going alphabetically, so it might take a week or so to get to this one.

**Comment by cferdinandi** [comment]
Added release tags. Will not registering officially with Bower.

**Comment by mahnunchik** [comment]
@cferdinandi Thanks!

What is the reason not to register in bower registry?

**Comment by cferdinandi** [comment]
There are a lot of package managers. Most support loading from GitHub, and they come and go in popularity quickly. It's one less thing for me to maintain or worry about.
