### ISSUE TITLE
Links to different pages

### ISSUE THREAD

**Issue by alcesleo** [cferdinandi/smooth-scroll#156]
Hey! I'm trying to use this in a navigation bar that spans multiple pages, which means that in some cases it should actually follow the link before scrolling, now it just scrolls on the same page. Is there an easy way of doing this?

Cheers!

**Comment by cferdinandi** [comment]
It's possible, relatively easily, using the API.   This should get you started: https://github.com/cferdinandi/smooth-scroll/issues/54

**Comment by alcesleo** [comment]
Great! Thank you :)
