### ISSUE TITLE
Feature detect Native Smooth Scrolling?

### ISSUE THREAD

**Issue by davidhund** [cferdinandi/smooth-scroll#158]
Apparently there's an API extension (Draft) to `scrollBy()` and `scrollTo()` coming providing this natively: http://dev.w3.org/csswg/cssom-view/

Writeup: http://blog.gospodarets.com/native_smooth_scrolling/

There's also a new `scroll-behavior:smooth` CSS property.

It might be good to add a feature-detect for these in smooth-scoll?

````
var isSmoothScrollSupported = 'scrollBehavior' in document.documentElement.style;
````

**Comment by cferdinandi** [comment]
@davidhund - Interesting thought. As this is still a (very) early stage, it gives me some time to think about how this might work. A few thoughts:

1. One approach could be to feature detect for the `scrollBehavior` API, and use that when supported.
2. The API, on initial read, does not support different easing methods. Instead, it simply uses the one supported by the browser. It also does not seem to allow you to control scroll speed. For that reason, I'm actually wondering if it makes sense to still use Smooth Scroll anyways as a developer may want more control than the native API provides.
3. I've done my best to make performance good with Smooth Scroll, but the native API would still provide better performance and is therefore worth considering.

As I talk this through, I think adding a configurable option for "native browser support" might be the best option. By default, it would always run the Smooth Scroll functions, but if you wanted, you could opt to use the native API when available.

Cheers for the suggestion!

**Comment by davidhund** [comment]
A configurable option sounds like a great plan.

**Comment by cferdinandi** [comment]
So it's been a crazy long time, and candidly, I don't think I'm actually going to ever implement this. As I think about this more, it'd be really for someone to just implement this today as such:

In their CSS file:

```css
[data-scroll] {
    scroll-behavior: smooth;
}
``` 

And in their JS file:

```js
if ( !'scrollBehavior' in document.documentElement.style ) {
    smoothScroll.init();
}
```

Accordingly, I'll be closing out this ticket. Thanks for bringing it to my attention, though.
