### ISSUE TITLE
use smooth-scroll with content nested in fixed wrapper

### ISSUE THREAD

**Issue by ChristopherNeuwirth** [cferdinandi/smooth-scroll#159]
hi there,
thank you for your awesome script. It really works great but currently I am facing an issue I can't solve: 
I made a page layout that has nested all of its content in a fixed div because the navigation is hided behind the content and gets only visible if the user clicks the burger button. that causes the page (actual the wrapper div) moving 284px to the left so that the body is visible (where the menu is placed). 

And that seems the problem why I can't get smooth-scroll to work. As soon as I remove the fixed attribute smooth-scroll starts scrolling. Is there a way to get smooth scrolling work within a fixed div? 

thank you for your reply
greetings,
chris

**Comment by cferdinandi** [comment]
Have a demo link you can share?

**Comment by ChristopherNeuwirth** [comment]
that's the base I used with the one exception that I set page positioning to fixed in order to get the scaling of cover bg images displayed proper.
http://apeatling.com/demos/smooth-menu/ 

everything of the content (where the anchor ids are) is nested in #page.

**Comment by cferdinandi** [comment]
There are no anchor links in that demo. Please provide a working demo I can look at. Otherwise I cannot help you.

**Comment by cferdinandi** [comment]
Closed due to non-responsiveness.
