### ISSUE TITLE
Animate scroll on linked page

### ISSUE THREAD

**Issue by bevels** [cferdinandi/smooth-scroll#162]
Firstly thanks for the great plugin, it's super easy to implement and work with!

Is it possible to animate the scroll of a page that's been linked to?

Ie.  `<a data-scroll href="http://www.site/secondpage/#lookatme">link to second page</a>`

On click you'd be redirected to '/secondpage' and then it animates scroll to '#lookatme'
 
Thanks

**Comment by cferdinandi** [comment]
Hi @bevels - Happy to hear you're enjoying the script! You can in fact do this, though it requires you to work with the extended API. This should get you started: https://github.com/cferdinandi/smooth-scroll/issues/54
