### ISSUE TITLE
doesn't work in browserify environment

### ISSUE THREAD

**Issue by alexbeletsky** [cferdinandi/smooth-scroll#163]
I'm trying to use the plugin with `browserify`, without much success, though.

The reason, seems to be, that in browserified apps `root` is not a window, but rather `module` object.

[Here](https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll.js#L18) the `.addEventListener` is always `undefined`, so plugin in not initialized correctly. My naive try to change to `window.addEventListener` didn't help, since `root` used in many other places.

I'm using browserify + umd modules quite a lot, but it's first time I'm having such issue. Maybe there are some workarounds with `browserify-shim` or something?

**Comment by cferdinandi** [comment]
Known issue. `root` SHOULD be window. Working to figure out how to address this, as Browserify is the one outlier here. Other UMD modules work fine, and the model for this script wrapper is based on the official UMD spec on GitHub.

See also: https://github.com/cferdinandi/smooth-scroll/pull/160

**Comment by alexbeletsky** [comment]
So far, my solution is. I've added `browserify-shim`, with following configuration,

```js
  "browser": {
    "smooth-scroll": "./node_modules/smooth-scroll/dist/js/smooth-scroll.js"
  },
  "browserify-shim": {
    "smooth-scroll": "smoothScroll"
  },
```

my code,

```js
var $ = require('jquery');
var smoothScroll = require('smooth-scroll');

$(function () {
	smoothScroll.init({
		speed: 700,
		easing: 'easeInOutCubic',
		updateURL: false
	});
});
```

```html
<a data-scroll href="#get-started" class="btn btn-xlg btn-green">...</a>
```

Works as expected. But it's a more workaround, rather the solution.

From my side, `root` is `window` in UMD is wrong. As I mentioned above, `root` is `module` not `window`. With `browserify-shim` `this` is actually `windows`, that's why it works fine.

The package has to be corrected to use `windows` explicitly. If you are fine with that, I can submit a PR.

**Comment by cferdinandi** [comment]
Sorry, I miswrote. You are correct. `this` should be passed in as `window` in Browserify, and it's not. The shim strikes me as something folks who want to Browserify should implement themselves.

**Comment by alexbeletsky** [comment]
I'm not sure that #160 is exactly right since it changes UMD signature.. But it almost does what it says, changes the `root` to `window`. But, it should not be done this way..

**Comment by cferdinandi** [comment]
I agree, @alexbeletsky. It also breaks other uses of UMD. One shouldn't redefine `root` in the module.

**Comment by cferdinandi** [comment]
Possible solution:

Source: https://gist.github.com/ifandelse/4617996

**Comment by cferdinandi** [comment]
See also:

* http://stackoverflow.com/questions/19946705/advice-to-resolve-window-dependency-when-running-in-node-js
* http://stackoverflow.com/questions/28610796/browserify-universal-module-definition-browser-node-different-dependencies

**Comment by alexbeletsky** [comment]
Yeah, it's actually quite a smart trick and really easy to integrate!

+1 for it :)

**Comment by alexbeletsky** [comment]
Yeah, it's actually quite a smart trick and really easy to integrate!

+1 for it :)

**Comment by cferdinandi** [comment]
Since I don't use Browserify myself, could you do me a HUGE favor and test it for me? If it works, I'll incorporate into the official script.

**Comment by alexbeletsky** [comment]
Submitted #164

**Comment by cferdinandi** [comment]
I just saw. Thank you so much!

**Comment by cferdinandi** [comment]
@alexbeletsky Thanks again for your help with this. All merged in and set to go. I added you to the list of contributors in the readme file.

Quick question: I've have some folks say they can't use this module with AMD/Common JS module tools because I don't currently have tagging enabled, but you seem to using it without issue. Is there something else I need to be doing? How did you make things work?

**Comment by alexbeletsky** [comment]
@cferdinandi you are welcome, thanks a lot for the great library!

I'm using that without issues, fetching your package not from `npm` but github directly, exactly as it's in your README file,

```bash
$ npm install cferdinandi/smooth-scroll
```

Then, in my `package.json` I have something like

```js
    "smooth-scroll": "git://github.com/cferdinandi/smooth-scroll"
```

What I think guys are talking about is [semver](http://semver.io/) support. As soon as you upload the new version, you need to tag it and push that tags. For the current version, all you need to do is,

```bash
$ git tag v5.3.7
$ git push --tags
```

Each time you upgrade, you should not forget to push new tag :)

ps. Will try new version tonight.

**Comment by cferdinandi** [comment]
@alexbeletsky Thanks! I'm going to have to retroactively add some tags. Cheers!
