### ISSUE TITLE
Offset in one direction only

### ISSUE THREAD

**Issue by Mellivora** [cferdinandi/smooth-scroll#167]
Many thanks for your work on this plugin.

I am using smooth-scroll as well as headroom.js so I only need an offset applied when scrolling back up the screen.

Is it possible to have an offset work only in one direction?

**Comment by cferdinandi** [comment]
Your best bet would be to use the [Smooth Scroll API.](https://github.com/cferdinandi/smooth-scroll#use-smooth-scroll-events-in-your-own-scripts) You would:

1. Listen for a click event.
2. When a `data-scroll` link is clicked, determine if the target link is higher or lower on the page than the current link.
3. Call the `smoothScroll.animateScroll()` method. Pass in an offset as an option only if you're scrolling up.

Out-of-the-box, the functionality isn't built in to Smooth Scroll, and it's such an edge case that I don't plan to add it.

**Comment by Mellivora** [comment]
That's great, thank you very much for your reply, I will try that.
