### ISSUE TITLE
npm install smooth-scroll name installs the wrong package

### ISSUE THREAD

**Issue by jordansexton** [cferdinandi/smooth-scroll#169]
```
npm install smooth-scroll
npm WARN deprecated smooth-scroll@1.5.0: Sorry! Bad naming issues. Please use the jquery-smooth-scroll package instead.
smooth-scroll@1.5.0 node_modules/smooth-scroll
└── jquery@2.1.4
```

Currently working around this by using this repo in my package.json.

**Comment by cferdinandi** [comment]
I don't believe that's my script. You need to explicitly call `cferdinandi/smooth-scroll`. See https://docs.npmjs.com/files/package.json#github-urls for more details.

**Comment by jordansexton** [comment]
Yes, but in light of that, your package.json is bad because the name given should correspond exactly with the name of the package in NPM.

**Comment by cferdinandi** [comment]
My `package.json` files is used to install the build tools I use to create the production versions of the scripts. It does not install or reference Smooth Scroll from NPM, as this script is not formally listed there.

Per the `readme.md`, please us `cferdinandi/smooth-scroll` to reference this script directly from GitHub. I've done it before. It works perfectly.

**Comment by jordansexton** [comment]
Okay. I'm not arguing with you there isn't a workaround. I acknowledged that's exactly what I'm doing in the original post. What I'm saying is that it's unintuitive and requires a byline in the readme and an unusual case for end users to install. Whether you want your package to be in NPM is a matter of opinion. The fact that it must be installed in a nonstandard way for an npm package.json-containing project, even if you personally only use it for dependencies, and is therefore inherently less intuitive to install than other packages following the accepted convention, is not a matter of opinion.

**Comment by jordansexton** [comment]
Anyway, I'm not trying to be pedantic. I appreciate the library and your work on it. It's just weird to read the name from a package.json, install it, and then get weird errors about jQuery.

**Comment by cferdinandi** [comment]
Yea, I can see that.

**Comment by cferdinandi** [comment]
I'm reading what I just wrote, and it comes across as crazy sarcastic even though I didn't mean it that way. What I meant was: That's a fair point, and I'll consider updating.
