### ISSUE TITLE
Not Body scroll

### ISSUE THREAD

**Issue by NeedHate** [cferdinandi/smooth-scroll#173]
Hi! Is it possible to make smooth scroll to work not on body element, for example, on ".container" element ? Seems to be trouble for me. 
Thanks!

**Comment by cferdinandi** [comment]
There is not, but that might be something I could support with some refactoring. Could you help me understand the use case for this?

**Comment by NeedHate** [comment]
Throw me with tomato. My structure was wrong. Its my brain: just after asking the question - i've got the answer. Apologies for worry.

**Comment by cferdinandi** [comment]
No worries!

**Comment by adrubio** [comment]
How did you manage to scroll in a .container?
