### ISSUE TITLE
Cannot find module 'buoy' in v7 of smooth-scroll

### ISSUE THREAD

**Issue by tscanlin** [cferdinandi/smooth-scroll#183]
Hey, I'm getting an error saying Cannot find module 'buoy' in the most recent version of smooth-scroll (v7). Not sure why though since in your release notes it says 'buoy' was removed.

I'm using version v0.10.28 of node so maybe that's causing it to not find the 'buoy' module?

Switching to 5.3.7 fixed the issue ("smooth-scroll": "git://github.com/cferdinandi/smooth-scroll.git#b5621ff47293b8ec957c271a72121254349f169e"). Then `npm install`

No rush on fixing this cause the old version works just fine, this is more just an fyi.

See below for the stack trace:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'buoy' from '/Users/timscanlin/Sites/developers.optimizely.com/node_modules/smooth-scroll/dist/js'
    at /Users/timscanlin/Sites/developers.optimizely.com/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/timscanlin/Sites/developers.optimizely.com/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/timscanlin/Sites/developers.optimizely.com/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/timscanlin/Sites/developers.optimizely.com/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/timscanlin/Sites/developers.optimizely.com/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/timscanlin/Sites/developers.optimizely.com/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

npm ERR! developers.optimizely.com@0.0.0 gulp: `gulp`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the developers.optimizely.com@0.0.0 gulp script.
npm ERR! This is most likely a problem with the developers.optimizely.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls developers.optimizely.com
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "/Users/timscanlin/.nvm/v0.10.28/bin/node" "/Users/timscanlin/.nvm/v0.10.28/bin/npm" "run" "gulp"
npm ERR! cwd /Users/timscanlin/Sites/developers.optimizely.com
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/timscanlin/Sites/developers.optimizely.com/npm-debug.log
npm ERR! not ok code 0
```

**Comment by cferdinandi** [comment]
@tscanlin In short: Because I'm an idiot. I made updates to the source but didn't run the build, so the `dist` directory still contains both Buoy itself and the previous iteration of the script that passed in Buoy as a dependency. This isn't a problem when loading the script the old fashion way, but when using module systems like Browserify, it will throw an error for the missing dependency.

I'll rerun the build and push an update in the next 15 minutes. Thanks for letting me know about this!

**Comment by cferdinandi** [comment]
Fixed

**Comment by tscanlin** [comment]
Thanks for fixing this so fast, you're awesome! :)

**Comment by cferdinandi** [comment]
Actually, I'm apparently not. I didn't do the things I needed to do. Oy, not enough coffee!

**Comment by cferdinandi** [comment]
Ok, properly fixed this time. Sorry!

You want v7.0.2. https://github.com/cferdinandi/smooth-scroll/pull/185

**Comment by tscanlin** [comment]
Cool, thank you!!
