### ISSUE TITLE
Events?

### ISSUE THREAD

**Issue by giovannipds** [cferdinandi/smooth-scroll#189]
Hello! I looked at the code quickly. Doesn't it dispatch events, hã? I think it would be a cool improvement. I'm using it in combination with Waypoints, so I'll need to check when it's scrolling to not perform Waypoints actions.

**Comment by cferdinandi** [comment]
@giovannipds It doesn't, but it does run a callback after the scroll is completed. If you're trying to do some sort of scrollspy functionality, you might choose to pair Smooth Scroll with [Gumshoe](https://github.com/cferdinandi/gumshoe).

**Comment by giovannipds** [comment]
Damn, sorry! I forgot to give you a feedback. Months later, thanks anyway. :+1:
