### ISSUE TITLE
Using smooth-scroll breaks `:target` CSS selectors

### ISSUE THREAD

**Issue by g105b** [cferdinandi/smooth-scroll#194]
Elements that are styled depending on the URL hash and element's ID using the `:target` CSS selector only work on page render or refresh, but if the hash changes by clicking a smooth-scrolled link the target element does not change.

**Comment by cferdinandi** [comment]
This is unfortunately a side effect of how the script works. The JS `pushState` API does not respect `:target`, causing the break. Updating the script to use `hash` instead would fix the `:target` issue, but result in a page jump, which defeats the purpose of using the script.

You might try using the `callback` option to assign an active class to the clicked link:

```js
```

**Comment by g105b** [comment]
Thanks for the advice. Does the callback scroll at the point of scrolling, or after the scroll animation completes?

**Comment by cferdinandi** [comment]
The callback runs after the animation has completed.
