### ISSUE TITLE
Error in Chrome when working with local file

### ISSUE THREAD

**Issue by lessless** [cferdinandi/smooth-scroll#195]
Hello there is an error when page is opened directly from disk:
```
Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///Users/rkr/projects/foo/index.html#howitworks' cannot be created in a document with origin 'null'.
```

is using web-server an only option? the source of error is here https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll.js#L312

**Comment by cferdinandi** [comment]
Unfortunately, `pushState` only works on a web-server. See https://code.google.com/p/chromium/issues/detail?id=301210 and http://stackoverflow.com/questions/13348766/securityerror-the-operation-is-insecure-window-history-pushstate. 

However, I just pushed [v7.1.1](https://github.com/cferdinandi/smooth-scroll/pull/196), which includes a check on the origin before running `pushState` to prevent the JS errors that stop the script from working. Thanks for the bug report!
