### ISSUE TITLE
TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by dsdenes** [cferdinandi/smooth-scroll#197]
$ npm install smooth-scroll
npm http GET https://registry.npmjs.org/smooth-scroll
npm http 404 https://registry.npmjs.org/smooth-scroll
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-63-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "smooth-scroll"
npm ERR! cwd /home/...
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/...
npm ERR! not ok code 0

$ node -v
v4.0.0

$ nodejs -v
v4.0.0

**Comment by cferdinandi** [comment]
https://github.com/cferdinandi/smooth-scroll#installing-with-package-managers
