### ISSUE TITLE
Bower component outdated

### ISSUE THREAD

**Issue by leolux** [cferdinandi/smooth-scroll#198]
In the bower registry there is currently only the version "1.0.0" registered. I noticed that your git version tags are not valid Semver tags (http://semver.org/).

I suggest to make this project a valid bower component again as explained in http://bower.io/docs/creating-packages/#register. It requires a valid bower.json file and git version tags without the leading "v". I think having two git tags for each version should do the trick and already pushed tags don't need to be deleted.

**Comment by cferdinandi** [comment]
This isn't registered in the shower registry (at least not by me). Per the docs, use git hooks with Bower. 

https://github.com/cferdinandi/smooth-scroll#installing-with-package-managers

**Comment by leolux** [comment]
There is some component registered with the name "smooth-scroll". You can check it yourself:
https://bower.herokuapp.com/packages/smooth-scroll

But bower returns a diffrent component with the same name: https://github.com/Yappli/smooth-scroll
My issue was based on the identical naming of both components which caused the confision.

So everything is fine and one should not expect the bower component "smooth-scroll" to be related to this project.

**Comment by leolux** [comment]
Thanks four your help cferdinandi!

**Comment by cferdinandi** [comment]
Yea, that's not mine.
