### ISSUE TITLE
Before scroll callback?

### ISSUE THREAD

**Issue by jenstornell** [cferdinandi/smooth-scroll#199]
This plugin works great. I use it together with Tabby. I trigger Tabby on click and then Smooth Scoll runs to that open tab.

**I use DOMtastic and it looks like this:**

```JS
$('.circles a').on('click', function(){
	$('[data-tab="' + $(this).attr('href') + '"]').trigger('click');
});
```

Now the page scrolls at the same time as it opens one of the tabs. It works but it would probably be better if there was a "before scroll callback" so it could open the tabs fully before starting the scoll. Now it feels like it does both at the same time. It feels a little jerkily, not so smooth.

What do you think?

**Comment by cferdinandi** [comment]
If it were me, I'd use tabby's callback function to run Smooth Scroll's `animateScroll()` method instead of triggering another click event. That let's you animate the scroll *after* the tab changes, which is your desired effect.
