### ISSUE TITLE
Question of beforeCallback or afterCallback?

### ISSUE THREAD

**Issue by kiuz** [cferdinandi/smooth-scroll#205]
hallo, i've used your code and work perfectly. But I can't get to work callbackBefore and callbackAfter... you can help me?

		smoothScroll.init({
			speed: 200,
			easing: 'easeInOutCubic',
			offset: 0,
			updateURL: true,
			callbackBefore: function ( toggle, anchor ) {
				window.alert("sometext");
			},
			callbackAfter: function ( toggle, anchor ) {
				window.alert("sometext");
			}			

		});

**Comment by cferdinandi** [comment]
Hi there... the timing-specific callback function (`callbackBefore` and `callbackAfter`) were deprecated a few versions ago in favor of a single `callback` method. See https://github.com/cferdinandi/smooth-scroll#global-settings for more details.

**Comment by kiuz** [comment]
OKay, thanks. But your index have old syntax ... 
https://github.com/cferdinandi/smooth-scroll/blob/master/index.html

**Comment by cferdinandi** [comment]
Good catch. I'll update.

**Comment by cferdinandi** [comment]
Updated
