### ISSUE TITLE
Advanced WordPress menu filter allows cross-page navigation

### ISSUE THREAD

**Issue by lkraav** [cferdinandi/smooth-scroll#206]
Follow up for #94. This should perhaps be a pull request on README.md. Let me know.

This will check whether the navigation menu links have been configured with any `#` anchors and if they point to the current page or somewhere else. All outbound links must avoid `data-scroll` attribute.

```php
add_filter( "nav_menu_link_attributes", function( $atts ) {

    if ( isset( $_SERVER["REQUEST_URI"] ) && $_SERVER["REQUEST_URI"] ) {

        if ( isset( $atts["href"] ) && false !== strpos( $atts["href"], $_SERVER["REQUEST_URI"] . "#" ) ) {

            $atts["data-scroll"] = "true";

        }

    }

    return $atts;

} );
```

Use `if ( isset( $_SERVER["REQUEST_URI"] ) && $REQUEST_URI = sanitize_text_field( wp_unslash( $_SERVER["REQUEST_URI"] ) ) ) {}` if you want to pass WordPress Coding Standards  (0.8.0) compliance.

**Comment by cferdinandi** [comment]
This is by far way better than my example, BUT... I'm actually leaning towards a JS-based implementation and will be updating the docs accordingly. See https://github.com/cferdinandi/smooth-scroll/issues/202 and https://github.com/cferdinandi/smooth-scroll/issues/201.

**Comment by cferdinandi** [comment]
I've decided to [update my readme with a JS-based approach](https://github.com/cferdinandi/smooth-scroll#programatically-adding-data-scroll-attributes-to-all-anchor-links) instead. Thanks for this, though!

**Comment by lkraav** [comment]
It doesn't look like the JS addresses the outbound links issue?

**Comment by cferdinandi** [comment]
You're quite right! Nice catch... I'll update accordingly...

**Comment by cferdinandi** [comment]
Fixed. Thanks again!

**Comment by lkraav** [comment]
That regex doesn't seem to address relative URL without a hostname?

**Comment by cferdinandi** [comment]
But if one omits the hostname, you could theoretically get some false positives in there.

**Comment by lkraav** [comment]
I'm not sure I follow. One example?

**Comment by cferdinandi** [comment]
Wouldn't `<a href="#something">Some link</a>` match as "internal and on this page" if you were on the homepage and the test only looked at the pathname, not the hostname?

Also, I just tested this using a domain without an explicit hostname. The browser infers one as the current domain when not including explicitly, so we should be all set.

**Comment by lkraav** [comment]
Cool beans. I'll hop back here if I find anything different from real world experiences later on. Thanks for the work :100:
