### ISSUE TITLE
Intercept the classes

### ISSUE THREAD

**Issue by kiuz** [cferdinandi/smooth-scroll#211]
With the Callback I can Intercept the classes of the DOM element clicked? 
I must operate on the element clicked after scrolling, not previosly.

Thanks a lot

**Comment by cferdinandi** [comment]
Hey there! As long as you pass the element in to your callback function, yes you can.

```js
smoothScroll.init({
    callback: function ( toggle, anchor ) {
        var clickedElemClass = toggle.className;
    }
});
```

**Comment by kiuz** [comment]
thanks and sorry for my many question ...

**Comment by cferdinandi** [comment]
No need to apologize... happy to help!
