### ISSUE TITLE
Question about updateURL parameter

### ISSUE THREAD

**Issue by benoitchantre** [cferdinandi/smooth-scroll#213]
> updateURL: true, // Boolean. Whether or not to update the URL with the anchor hash on scroll

When I init smoothScroll with the `updateURL` parameter value to `true`, the URL is updated when I click on a link, but not after a normal scroll (not triggered by a click on an anchor link).

Is it the expected behavior, or is it supposed to update the URL when the destination of the link enters in the viewport.

**Comment by cferdinandi** [comment]
The expected behavior of `updateURL` is that `data-scroll` smooth scroll links will update the URL with the anchor hash of the clicked anchor element.
