### ISSUE TITLE
Anchor ID removal causes flickering in DOM

### ISSUE THREAD

**Issue by jkallunki** [cferdinandi/smooth-scroll#216]
If there are CSS styles that depend on the anchor ID, every time the ID is removed and readded the DOM is re-rendered, which causes some nasty flickering and jumping. I don't think that this is a big issue since it can be prevented easily by not using IDs in CSS selectors, but maybe it should be added in the known issues so that it will be easier to spot?

**Comment by cferdinandi** [comment]
Good call. I'll update the readme asap.

**Comment by cferdinandi** [comment]
Done
