### ISSUE TITLE
8.0.0 Throws TypeError when animating

### ISSUE THREAD

**Issue by sdtsui** [cferdinandi/smooth-scroll#220]
Sweet package sir. FYI: I'm running this in prod and the most recent release broke scrolling functionality `onclick`.

I think the 'toggle' parameter is passed in as a string in `8.0.0`, and throws on line 337 when `toggle.getAttribute('data-options')` is called. 

Of note: in `8.0.0`, `toggle` is the *second paramater*. Here (screenshot, of 7.1.1 code), it is the first paramter.  This is probably it (line 335).
![7.1.1 code](http://puu.sh/mKZqQ/31decda9ee.png)

I hope that helps. Rolling back to `7.1.1` for now, and would appreciate confirmation if you plan on keeping the signature the same (we will likely stay on `7.1.1` if so). Thanks!

**Comment by cferdinandi** [comment]
Unable to reproduce. There's only one spot in the entire script where I call `getAttribute` on `toggle`, and I'm checking to make sure it exists before doing so:

```js
var overrides = getDataOptions( toggle ? toggle.getAttribute('data-options') : null );
```
