### ISSUE TITLE
Add main faile to bower json

### ISSUE THREAD

**Issue by Tibicenas** [cferdinandi/smooth-scroll#221]
Hi !
Some of us use gulp or grunt  to automate dependency injection : )

can you add the path to smooth-scroll.min.js file in your bower.json ? just will take a second 
```json
"main": [
    "FoldersPath/smooth-scroll.min.js"
  ],
```
Thanks in advance :+1:

**Comment by cferdinandi** [comment]
I don't have a bower.json file in Smooth Scroll, nor do I intended to do so. Please see https://github.com/cferdinandi/smooth-scroll/search?q=bower&type=Issues&utf8=%E2%9C%93

I do have a `main` key in package.json. Can you use that?

**Comment by Tibicenas** [comment]
Oh right,
 i'll try with the package.json, in that case,  can you add the min.js?
Not only the uncompressed version. and we'll avoid one of them if we need to :) 
Thank you by the fast reply :+1:

**Comment by cferdinandi** [comment]
Doh, I actually meant to do that in the first place. Nice catch! Addressed with v8.1.0: https://github.com/cferdinandi/smooth-scroll/pull/222
