### ISSUE TITLE
Jumping occuring when scrolling multiple times.

### ISSUE THREAD

**Issue by ianshade** [cferdinandi/smooth-scroll#225]
Hi!
I found a possible issue, reproducible in the demo so I hope it's not the case of me doing something wrong.
When you go to the demo, click let's say "Quint" - you're correctly smooth-scrolled to #bazinga, but then when you scroll with your mouse to the top of the page and click "Quint" once again, the page jumps to #bazinga for a second and then the correct animation from top begins. It does not happen all the time so you may need to play a few times - click, scroll up, click... but it seems to be quite visible with certain easings.

**Comment by cferdinandi** [comment]
I'm noticing numerous little issues with v8, unfortunately. A bigger one: it just flat out doesn't work (and breaks default anchor link behavior) in Chrome for iOS. I'll be reverting back to the old v7 structure, I think.

Thank you for letting me know about this. It's the straw that breaks the camels back.

**Comment by cferdinandi** [comment]
Should be fixed with https://github.com/cferdinandi/smooth-scroll/pull/226
