### ISSUE TITLE
smoothScroll  no longer works with react

### ISSUE THREAD

**Issue by Plummat** [cferdinandi/smooth-scroll#228]
.getAttribute is not a function is now returned

**Comment by Plummat** [comment]
Nevermind, it appears in your animateScroll, you changed the toggle and anchor locations in the params, so everything went haywire.

**Comment by cferdinandi** [comment]
Indeed. Just an FYI for future updates: Smooth Scroll using semantic versioning, so major version updates are breaking changes.
