### ISSUE TITLE
Smooth Scroll if already on same page?

### ISSUE THREAD

**Issue by jhall39** [cferdinandi/smooth-scroll#234]
Is it possible to setup this Smooth Scroll script to have it scroll to an anchor if it's already on the same page? I know it's weird and janky if you try to have it go to a page and then scroll down to the anchor within that page, but can it detect if I'm already on the same page as the anchor and scroll up or down to it?

**Comment by cferdinandi** [comment]
Unless I'm misunderstanding your question... that's the entire purpose of this script: to scroll to anchor links on the page you're already on.

**Comment by jhall39** [comment]
Say I have a navigation menu that shows up on several pages. It links to each page individually, but then there are dropdown elements that link to sections within each page as well. So I could be on Page 1, but then click on a link to go to a section on Page 2. 
Currently it works if I already am on the same page. It will scroll down to the section I want. But if I click on a section on another page.. it does nothing. It won't switch to that page. It doesn't smoothly scroll either, but that's because the section doesn't exist on the current page.
Additionally, two of my pages do have the same section in them. If I click the link for that section that is listed on one page, but while I am looking at the other page with the same section then it will simply scroll down to that section on the page I'm already on.
So it'd be cool if it recognized when the link isn't the current page and it should pass that through to the browser.
Sorry I didn't explain this at all the first go-around. I blame it on Monday and low caffeine levels.

**Comment by cferdinandi** [comment]
Please consult the readme: https://github.com/cferdinandi/smooth-scroll#animating-links-to-other-pages

**Comment by jhall39** [comment]
I don't really want it to scroll to a link on another page. I just wanted it to smooth scroll if on the same page or open it as normal if it's another page. As it is, it won't even open a link if it has data-scroll on it and it's not on the same page.

**Comment by cferdinandi** [comment]
Short answer: You need to use JS to dynamically add the `data-scroll` attribute before calling `init`.

Long answer: Get all links with a hash value, check if they point to the current page or not, and if they do, add `data-scroll`. THEN init.

I pointed you to the readme because you can use that code as a base for what you're trying to do.
