### ISSUE TITLE
Default settings not applied correctly

### ISSUE THREAD

**Issue by jancurn** [cferdinandi/smooth-scroll#236]
We're using smooth-scroll in a Meteor app, testing it in Google Chrome (version 48.0.2564.109 (64-bit), running on Mac OS X 10.10.5). The problem is that default settings passed to `init()` function are not used by `animateScroll()` function, because a local variable called `settings` clashes with an outer-scope variable `settings`, which contains the default settings. We work around that using by replacing:
```javascript
	smoothScroll.animateScroll = function ( anchor, toggle, options ) {

		// Options and overrides
		var overrides = getDataOptions( toggle ? toggle.getAttribute('data-options') : null );
		var settings = extend( settings || defaults, options || {}, overrides ); // Merge user options with defaults
       ...
```
with
```javascript
	smoothScroll.animateScroll = function ( anchor, toggle, options ) {
		// Options and overrides
		var overrides = getDataOptions( toggle ? toggle.getAttribute('data-options') : null );
		var effectiveSettings = extend( settings || defaults, options || {}, overrides ); // Merge user options with defaults
       ...
```
It would be great if this code was in the official release, so that we don't need to keep a separate version.

**Comment by cferdinandi** [comment]
@jancurn Hmm... In my testing, the global settings variable was being used, but I'd rather bullet-proof this, so I'd be happy to make this change. Thanks for letting me know!

**Comment by jancurn** [comment]
Yeah, I assumed so, but it really fails for me. Many thanks for your great tool and a quick response!

**Comment by cferdinandi** [comment]
This should be fixed with https://github.com/cferdinandi/smooth-scroll/pull/237
