### ISSUE TITLE
feature from version 4.0

### ISSUE THREAD

**Issue by hanskoff** [cferdinandi/smooth-scroll#239]
Hi, I love you script and I'm happy user of it. But I'm stack with 4.0 version because of feature "don't change address or location" as I use your script with angular this feature is important. I gave a peek on the code and have seen current version base on address so I predict there is no easy way to bring back that feature, am I wrong? :)

**Comment by cferdinandi** [comment]
I'm sorry, could you clarify what feature you're referring to? Do you mean the option to disable updating the URL on click/scroll?

**Comment by hanskoff** [comment]
yes, exactly that feature, function name in version 4.0 is `var _updateURL = function ( url, anchor )`

**Comment by cferdinandi** [comment]
That featured has been in every major version release except version 8, and was restored in version 9.

Checked the docs: https://github.com/cferdinandi/smooth-scroll#global-settings
