### ISSUE TITLE
Scroll to ID when checkbox is selected

### ISSUE THREAD

**Issue by PrestaShark** [cferdinandi/smooth-scroll#240]
Hi,
Any ideas how to use smooth-scroll when checkbox is selected?
Scenario: when checkbox is selected with "Terms of use" targets to "Payment methods" with id="payments"

Thanks for any hint :)

**Comment by cferdinandi** [comment]
I'd add a data attribute with the Terms of Use ID in it, add an event listener, and use the [animateScroll API](https://github.com/cferdinandi/smooth-scroll#animatescroll). Something like this:

```html
<label>
    <input data-scroll-target="#tos" type="checkbox" name="tos-checkbox" id="tos-checkbox" value="1">
   I accept the terms of use
</label>
...
<div id="tos">Some TOS stuff in here...</div>
```

```js
var tosCheckbox = document.querySelector( '#tos-checkbox' );
tosCheckbox.addEventListener('click', function (event) {
    var target = tosCheckbox.getAttribute( 'data-scroll-target' );
    smoothScroll.animateScroll( target );
}, false );
```
