### ISSUE TITLE
Invalid left-hand side expression

### ISSUE THREAD

**Issue by digi-brains** [cferdinandi/smooth-scroll#251]
When using the min version from the /dist directory I get:
`Invalid left-hand side expression in postfix operation`
I don't get this error in the un-minified version from /dist or /src

**Comment by cferdinandi** [comment]
Hi, can you give me a bit more info?

1. When does this error happen?
2. What does your init look like?
3. What browser and OS are you using?

Thanks in advance!

**Comment by digi-brains** [comment]
A. Thank you for the prompt response.
B. I swear I double checked it before I posted this issue, but my init looked like crap.

Nothing to see here.

Thank you.

**Comment by cferdinandi** [comment]
All good, and glad you got it figured out! Cheers!
