### ISSUE TITLE
e.hasAttribute error on click when rendered with vue.js

### ISSUE THREAD

**Issue by FKobus** [cferdinandi/smooth-scroll#252]
Because of the aggressive eventHandling (always checking on clicks) there was a problem with vue.js when elements are generated with html comments.

Within this event trigger it's looking for elements that match the settings. ie: [data-scroll] but when a parentNode is a html comment <span></span> it fails on elem.hasAttribute() because the selected elem is a comment node and not a element:

http://www.w3schools.com/jsref/prop_node_nodetype.asp

Therefore I changed:

`for ( ; elem && elem !== document; elem = elem.parentNode ) {`

to:

`for ( ; elem && elem !== document && elem.nodeType === 1; elem = elem.parentNode ) {`

to fix it.

I think a hard check on elem.nodeType is required to make sure elem.hasAttribute is valid.

**Comment by cferdinandi** [comment]
Hi, thanks for this. Would you mind pointing me to a working example just so I can see the error being thrown. This seems like a simple fix (thanks for the well done PR), but I want to get a hands on look first.

Cheers!

**Comment by FKobus** [comment]
I tried setting up a jsfiddle, but it doesn't render the fragments like vue.js does.
The sample html code looks like this:
```
  <ul class="ocm-pagination">
    <!--v-for-start-->
      <!--fragment-start-->
        <li class="ocm-pagination__page">
          <a class="ocm-pagination__link is-active" href="#page-1">1</a><!--v-if-->
        </li><!--v-if-->
      <!--fragment-end-->
    <!--v-for-end-->
  </ul>
```

**Comment by cferdinandi** [comment]
Weird that comments are getting picked up like that, but this is good enough for me. Thank you SO much for updating the version numbers in the PR, btw. I'll go push updates now. Thanks!
