### ISSUE TITLE
smoothScroll inside different js-flickity cells.

### ISSUE THREAD

**Issue by inspiredlabs** [cferdinandi/smooth-scroll#256]
Adding `data-scroll` breaks each anchor inside different js-flickity cells.
https://jsfiddle.net/5hq17ccn

What I'm trying to achieve is smoothScroll inside each js-flickity cell.

**Comment by cferdinandi** [comment]
`data-scroll` is not used anywhere in that HTML, and even if you remove `smoothScroll.init`, the links still don't work. This is not a bug with Smooth Scroll.

**Comment by cferdinandi** [comment]
Actually, figured this one out. Your containing element has a fixed height with `overflow: hidden`. See [Known Issues](https://github.com/cferdinandi/smooth-scroll#body-styling) for more details.

**Comment by inspiredlabs** [comment]
Can you help me update the fiddle? Because, I can't get the following to work, presuming `overflow: hidden` refers to this:
`.flickity-viewport {
  /*overflow: hidden;*/
  position: relative;
  height: 100%;
}`

After I added `data-scroll` like this:  `<a data-scroll href="#moe">Moe</a>` back in to each anchor. They seem to have stopped working again.

Here's a demo: https://jsfiddle.net/5hq17ccn/6/

**Comment by cferdinandi** [comment]
This was causing the problem in your CSS:

```css
.gallery-cell {
    ...
    height: 100vh!important;
    ...
}
```

I commented it out and things are working now, but your arrows and dots are not positioned properly.

**Comment by cferdinandi** [comment]
https://jsfiddle.net/5hq17ccn/9/

**Comment by inspiredlabs** [comment]
Ok. Thank you. Whilst I can tinker with the arrows and dots, it's learning how to get the most out of  `smoothScroll ` and `gumshoe` I'm struggling with.

Now for example there's two new issues I'm looking at: both of the cells scroll the same amount (this seems to only happen with `data-scroll`), and the `gumshoe` component with inline `position:absolute` no longer sticks to the top.

**Comment by cferdinandi** [comment]
I'm terribly sorry, but I can't provide CSS debug/design support.

**Comment by inspiredlabs** [comment]
That's fine. Is there an example that I can look at that works in different containers? The supplied example ([https://cferdinandi.github.io/gumshoe]) only seems to act as a guide for content inside one container.

Correct me if I'm wrong, but the example I'm looking for should walk me through how `gumshoe.getCurrentNav();` works in different containers? In my case inside different js-flickity cells.

**Comment by cferdinandi** [comment]
I don't, sorry. The way you're using Gumshoe is a bit outside of the intended use case for the script.
