### ISSUE TITLE
Using smooth-scroll

### ISSUE THREAD

**Issue by tscanlin** [cferdinandi/smooth-scroll#257]
Hey, feel free to close this issue, but I just wanted to reach out and let you know that I have announced a project called Tocbot which makes use of smooth-scroll as its only dependency. It generates a table of contents from headings in a document and uses smooth-scroll to provide a smooth transition between them. If you have any feedback I'd love to hear it!
http://tscanlin.github.io/tocbot/

I love the work you've done with smooth-scroll and just wanted to thank you for open sourcing it for the community to benefit from. You have a great API and good documentation. Keep it up! :+1:

**Comment by cferdinandi** [comment]
Hi @tscanlin - That's really cool! I've built things like that in the past (see https://cferdinandi.github.io/kraken), but nothing as well done and programatic as this. Definitely using your script on future projects.

Loving this! Thanks!

**Comment by tscanlin** [comment]
Nice, Kraken looks really neat too! Thanks for the praise, I hope you have a good day!
