### ISSUE TITLE
requestAnimationFrame for better performance?

### ISSUE THREAD

**Issue by erhnsn** [cferdinandi/smooth-scroll#258]
Why is setTimeout instead of requestAnimationFrame used for the throttleing? I know this has been reported before 

https://github.com/cferdinandi/smooth-scroll/issues/224

But there's a really simple polyfill here https://gist.github.com/paulirish/1579671

**Comment by cferdinandi** [comment]
1. Thanks for doing your homework, and for locating the polyfill.
2. In addition to more backwards compatibility, I just haven't wanted to rewrite that section of the script when it works "good enough" already.
