### ISSUE TITLE
Using smooth scroll prevents use of :target css selector

### ISSUE THREAD

**Issue by seanfoo** [cferdinandi/smooth-scroll#263]
I suspect this is an issue that is a browser implementation issue, but I thought I would mention it incase it's not.  

The desired behavior can be seen here:
https://css-tricks.com/on-target/

there is a bug in the article that may be on point for this project.
https://bugs.webkit.org/show_bug.cgi?id=83490

To recreate, add

:target { background-color:yellow; }   to a page using smooth-scroll and then click on a smooth scroll link.  the target won't light up.  If you reload the page it does.

Thanks for the project.  Find it quite useful.

**Comment by cferdinandi** [comment]
Known issue, no workaround, as there's no way to programatically set the scrolled to element with the `:target` pseudo.

Accordingly, closing as won't fix.

**Comment by cferdinandi** [comment]
Should have mentioned: thanks for the issue, and the links!

**Comment by mikhailovenator** [comment]
It works in IE11
