### ISSUE TITLE
Not working when body is not element to scroll

### ISSUE THREAD

**Issue by nicolas-goudry** [cferdinandi/smooth-scroll#264]
Hello,

Nice work you did here!

I’m stuck right now because in my project, the body isn’t the element to scroll…

I have this markup :

```html
<body class="app">
  <header data-scroll-header></header>
  <ul class="nav">
    <li>
      <a data-scroll href="#home">Home</a>
    </li>
  </ul>
  <main></main>
</body>
```

`body` is `overflow: hidden;`
`header` is `position: fixed; height: 3rem;`
`main` is `height: calc(100% - 3rem); margin-top: 3rem;`

That way the scrollbar begins inside the main container.

I’m using Chome 52 on Windows (sic) 10 (re-sic)!

Would love an option to set target container to scroll :smile: 

Thanks!

**Comment by cferdinandi** [comment]
Known issue: https://github.com/cferdinandi/smooth-scroll#body-styling
