### ISSUE TITLE
Doesn't scroll due to getEndLocation() working incorrectly

### ISSUE THREAD

**Issue by gtaubman** [cferdinandi/smooth-scroll#265]
Hello!

I downloaded the the zip file from your github page (https://github.com/cferdinandi/smooth-scroll/archive/master.zip) and scrolling in that build doesn't work because of a bug in getEndLocation().  The bug is that getEndLocation() always returns 0 because of the return line.

Changing the following line:

`return Math.min(location, getDocumentHeight() - getViewportHeight());`

to:

`return Math.min(location, getDocumentHeight());`

fixes the problem, although I'm not sure it's the correct fix.  Just wanted to let you know!

**Comment by cferdinandi** [comment]
I just tested it and it's working fine for me in a few browsers. What OS/browser/version # are you using?

**Comment by gtaubman** [comment]
Hmm!  That's surprising!  I'm on OS X 10.11.5 using Chrome 51.0.2704.63.

**Comment by cferdinandi** [comment]
Weird, we're running the exact same setup. I tested in Firefox, too.

Are you referring to the demo in `/docs/index.html` or a site you're building? If it's the latter, can you share a demo with me?

**Comment by gtaubman** [comment]
Sorry for the slow response.  It was a site I'm building.  One thing I
remember is that I didn't have a <meta viewport> set at the time.  Could
that possibly be the culprit?  I plan to confirm on my end but haven't had
a chance lately.

**Comment by cferdinandi** [comment]
I suspect your issue may be more related to one of the [known issues](https://github.com/cferdinandi/smooth-scroll#known-issues), but until you provide me with a live, working demo, I can't say.

I'm going to close this issue since I can't replicate it. If you want to [provide a reduced test](https://github.com/cferdinandi/smooth-scroll/blob/master/CONTRIBUTING.md#reporting-a-bug) I'll be happy to reopen it, though.

**Comment by bruce-one** [comment]
I know this is an old issue, but I encountered something similar (it had the same effect and symptoms) and it was because I didn't have a doctype (ie adding the HTML5 doctype (`<!DOCTYPE html>`) fixed it for me) :-)

Just in case anyone encounters a similar issue, that might be it :-)

**Comment by cferdinandi** [comment]
@bruce-one That's bizarre! Thanks for posting this here!
