### ISSUE TITLE
Providing an integer to animateScroll throws an error

### ISSUE THREAD

**Issue by yhuard** [cferdinandi/smooth-scroll#277]
Since #272, if we provide an integer to animateScroll, the script fails: `Uncaught TypeError: id.charAt is not a function` in `escapeCharacters`.

**Comment by cferdinandi** [comment]
Good catch! Should be fixed with https://github.com/cferdinandi/smooth-scroll/pull/278

**Comment by yhuard** [comment]
I can confirm that it's now fixed, thank you!

**Comment by cferdinandi** [comment]
Awesome, and thank you so much for letting me known about this!
