### ISSUE TITLE
updateURL option

### ISSUE THREAD

**Issue by stevenle** [cferdinandi/smooth-scroll#287]
I think there used to be an `updateURL` option and I noticed it's been removed. I'm wondering if you could point me to the commit where it was removed so that I could point my dependency at an earlier version where that option was still available? Thanks, appreciate it!

**Comment by cferdinandi** [comment]
This was a major version release change with [version 10.x](https://github.com/cferdinandi/smooth-scroll/releases/tag/v10.0.0) about two weeks ago. The script was completely rewritten with a dependency on hashes to work.

Any 9.x version will support the `updateURL` option still: https://github.com/cferdinandi/smooth-scroll/releases

**Comment by Mexikaner9** [comment]
can  you please add the updateURL function?

**Comment by cferdinandi** [comment]
@Mexikaner9 see above
