### ISSUE TITLE
#link in URL bar

### ISSUE THREAD

**Issue by exxosuk** [cferdinandi/smooth-scroll#288]
First of all thanks for your hard work on this, after trying to get Jquery to work and other JS examples all day it has been driving me nuts!  

All looks to work OK, not spotted any bugs or anything, but one thing which might not really be a bug, is the hash link appears in the URL bar such as #smooth-scroll-top.. Is there a way to stop the #link from appearing in the URL bar ?  I'm using the latest version.   Thanks.

**Comment by cferdinandi** [comment]
This happens only if no hash is provided, starting with version 10 (a major, breaking change—I use semantic versioning).

For empty hash values (`href="#"`), a hash string is forced because v10 requires a hashchange event to toggle scrolling. No way to avoid other than specifying an ID (ex. `#top`).

**Comment by exxosuk** [comment]
It happens with all the #links  like #TOP #MIDDLE #BOTTOM  .  I used just # for the top link because I used #TOP before and when it went to the top the vertical was juddering a couple of pixels very fast up and down.

**Comment by exxosuk** [comment]
Your own example does the same, so is it supposed to do that or not, im confused. 

http://cferdinandi.github.io/smooth-scroll/#smooth-scroll-top
http://cferdinandi.github.io/smooth-scroll/#bazinga

**Comment by cferdinandi** [comment]
Ooohhh... I misread your question. You're asking how to prevent the hash from displaying in the URL. You can't.

This was supported in version 9.x and lower. It was removed in version 10.x. Please see https://github.com/cferdinandi/smooth-scroll/releases for more.

**Comment by exxosuk** [comment]
:)  So its "by design" then for better browser compatibility.  I think I tried  a previous version last night (cant remember which one) and I don't think the scroll worked in IE9.   

So I have a new problem then, that your link such as http://cferdinandi.github.io/smooth-scroll/#bazinga  will go right to the #bazinga anchor on your page, but this doesn't seem to work on my page.  I have buttons with links, when they are clicked, the scroll works, but doesn't on page load.  Its was why I was trying to remove the hash from the URL bar to stop people from copying the full URL.. nothing like going around in circles is there :)

**Comment by exxosuk** [comment]
I've put #TOP in the link now, so I get #TOP and not #smooth-scroll-top but now when I click a link and it scrolls down... when I click "back to top link" it goes to the top without scrolling.  If I manually scroll down to the page and click "back to top link" it scrolls up as normal. 

I don't really get what going on with all this stuff, always seems to be some niggle somewhere with all the methods ive tried so far with various frameworks.  Do you have PM I can send you the URL to take a look at, id rather not post it here for now as its a WIP page.

**Comment by cferdinandi** [comment]
[Version 9.x should work on IE 9 as well.](https://github.com/cferdinandi/smooth-scroll/tree/7f32bdb6cbec675b528d09966778d0413bca746a#browser-compatibility)

You can email me the link if you'd like: https://gomakethings.com/about/

**Comment by exxosuk** [comment]
Thanks will email now with info.

**Comment by cferdinandi** [comment]
It's the easing pattern you're using. For some reason, the math is acting wonky. Remove `data-options` from the URL itself and the link works as expected.
