### ISSUE TITLE
Timeout / Delay before scroll?

### ISSUE THREAD

**Issue by dblodorn** [cferdinandi/smooth-scroll#289]
Hi! awesome plugin - totally essential in my book. - Thanks!

This is more of a feature request, is there a possibility to place a delay before the scroll event? I don't see this in the api, would this be possible with a callback, or need to be built into the plugin?

Thanks! And would love to hear your opinion! @cferdinandi 

My scenario: User clicks an anchor link on a dropdown menu that covers the screen, I would like the menu to complete its animation post click, and then initiate the scroll.

**Comment by cferdinandi** [comment]
Hi there! I wouldn't want to bake this into the core code, but it is easily supported via the Smooth Scroll API today—specifically, [the `animateScroll` method](https://github.com/cferdinandi/smooth-scroll#animatescroll).

In your case, don't add `data-scroll` to the link, and instead grab the anchor yourself and call `animateScroll` after the menu closes in your JS. Does that help?

**Comment by dblodorn** [comment]
Great! Thank you so much @cferdinandi
