### ISSUE TITLE
Position: fixed elements turn to Position: relative during smoot-scroll on iOS

### ISSUE THREAD

**Issue by AnnaKosolapova** [cferdinandi/smooth-scroll#295]
I have a header which is positioned as fixed and implemented scrolling (on click on one div, page scrolls to that particular div, offsetted with header height). So all works perfect on desktop, like magic, my page scrolls to that div and header scrolls down together and sits on top of the div (no matter how narrow is it). But when I'm trying to test it from iPhone's Safari it looks like after scroll has been performed my header sticks to the top of the document (like it's position relative) and I can get it back only by refreshing the page.

I would highly appreciate if you share any thoughts around that.
Thank you in advance.

**Comment by cferdinandi** [comment]
Do you have a link I can look at?

**Comment by AnnaKosolapova** [comment]
Let me get back to you when I reproduce it. Can close the issue for now.

**Comment by AnnaKosolapova** [comment]
Ok, I reproduces it using the `bazinga` example in the repo.

Unfortunately I don't have permissions to commit to this repo in a fork, so I'll just insert a file here.

```
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<title>Smooth Scroll</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- stylesheets -->
		<style type="text/css">
			body {
				max-width: 40em;
				width: 88%;
				margin-left: auto;
				margin-right: auto;
			}
      .header {
        background: black;
        height: 50px;
        flex-shrink: 0;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 999;
      }
		</style>
	</head>

	<body>
    <div class="header">
    </div>

		<main id="top">

			<nav>
				<h1>Smooth Scroll</h1>
				<p><a href="https://github.com/cferdinandi/smooth-scroll">GitHub</a></p>
				<hr>
			</nav>

			<section>
<p>
    <strong>Linear</strong><br>
    <a data-scroll data-options='{ "easing": "linear" }' href="#bazinga">Linear (no other options)</a><br>
</p>

<div id="searchBar">
  <h6>Search</h6>
  <input type="text" />
</div>

<p>
    <strong>Ease-In</strong><br>
    <a data-scroll data-options='{ "easing": "easeInQuad" }' href="#bazinga">Quad</a><br>
    <a data-scroll data-options='{ "easing": "easeInCubic" }' href="#bazinga">Cubic</a><br>
    <a data-scroll data-options='{ "easing": "easeInQuart" }' href="#bazinga">Quart</a><br>
    <a data-scroll data-options='{ "easing": "easeInQuint" }' href="#bazinga">Quint</a>
</p>

<p>
    <strong>Ease-In-Out</strong><br>
    <a data-scroll data-options='{ "easing": "easeInOutQuad" }' href="#bazinga">Quad</a><br>
    <a data-scroll data-options='{ "easing": "easeInOutCubic" }' href="#bazinga">Cubic</a><br>
    <a data-scroll data-options='{ "easing": "easeInOutQuart" }' href="#bazinga">Quart</a><br>
    <a data-scroll data-options='{ "easing": "easeInOutQuint" }' href="#bazinga">Quint</a>
</p>

<p>
    <strong>Ease-Out</strong><br>
    <a data-scroll data-options='{ "easing": "easeOutQuad" }' href="#bazinga">Quad</a><br>
    <a data-scroll data-options='{ "easing": "easeOutCubic" }' href="#bazinga">Cubic</a><br>
    <a data-scroll data-options='{ "easing": "easeOutQuart" }' href="#bazinga">Quart</a><br>
    <a data-scroll data-options='{ "easing": "easeOutQuint" }' href="#bazinga">Quint</a>
</p>

<p>
    .<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>
    .<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>
    .<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.
</p>

<p id="bazinga"><a data-scroll href="#1@#%^-bottom">Bazinga!</a></p>

<p>
    .<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>
    .<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>
    .<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.
</p>

<p id="1@#%^-bottom"><a data-scroll data-options='{ "easing": "easeOutCubic" }' href="#">Back to the top</a></p>
			</section>
		</main>

		<!-- Javascript -->
		<script src="dist/js/smooth-scroll.js"></script>
		<script>
			smoothScroll.init();

      document.getElementById('searchBar').onclick = function(){
        var target = document.getElementById('searchBar');

        var focusOnSearch = function() {
          var searchBar = document.getElementById('searchBar');
          var input = searchBar.getElementsByTagName('input')[0];
          input.focus();
        };

        smoothScroll.animateScroll(target, null, {
          easing: 'easeInOutCubic',
          offset: 50,
          speed: 600,
          updateURL: false,
          callback:focusOnSearch, 
      });
      };
		</script>


	</body>
</html>
```

**Comment by cferdinandi** [comment]
Can you please post a working example on a live link I can access? The pasted code includes Git commit conflict tags, so I'm not entirely sure what I should be looking at here...

**Comment by AnnaKosolapova** [comment]
These are not git conflicts, sorry for confusing you. I've just marked newly inserted code like that.
This is a file from smooth-scroll repository `/smooth-scroll/docs/index.html`

**Comment by cferdinandi** [comment]
Still, can you please set up a link or demo somewhere replicating the issue that I can take a look at?

**Comment by AnnaKosolapova** [comment]
Ok...will try to push live your repo somewhere tomorrow...thanks

**Comment by AnnaKosolapova** [comment]
Please use the following url 
http://10a9d2c6.ngrok.io

**Comment by AnnaKosolapova** [comment]
To run it locally, just copy code provided into your `/smooth-scroll/docs/index.html` file, and serve it from terminal by running the command `python -m SimpleHTTPServer 8000` from directory. Then you can access the port from your mobile phone, but going to url eg. `XXX.XXX.X.XXX:8000`, where `XXX.XXX.X.XXX` is your IP address.

To reproduce issue itself:
- open in iOS Safari
- when you're at the top of the page, click on Search area, smoth-scroll will scroll to this area, however fixed header does not follow the scroll and stays fixed at the top. 
- if you refresh and try to scroll manually, you can see that header follows the scroll as any normal fixed element is supposed to

**Comment by cferdinandi** [comment]
I'm sorry to keep harping on this, but can you please publish a working demo *on the web* so I can just open and view it in a browser?

I don't care if it's on CodePen or JSFiddle, or a just a simple HTML file hosted on your own site.

**Comment by AnnaKosolapova** [comment]
Could you please explain what's wrong with the link I've provided above? http://10a9d2c6.ngrok.io

**Comment by cferdinandi** [comment]
Ah, sorry. Your instructions around running it locally made me think that was something I needed to download and install. Looking at this now.

**Comment by AnnaKosolapova** [comment]
No, you don't need to download or install anything, you just need to fix an example in smooth-scroll repository. You can temporarily give me permissions to commit and I'll fork and push these changes into a branch here if it will be more understandable, so you'll see the diff.

**Comment by cferdinandi** [comment]
This seems to be related to iOS's zoom behavior and not Smooth Scroll. For example, open up the page, **don't** click on the search bar, and then pinch-and-zoom in anywhere on the page.

Now just scroll around normally (ie, not clicking a link). See how the fixed header disappears? This seems to be a known issue: http://stackoverflow.com/questions/15254095/issues-with-fixed-header-footer-and-side-bar-on-ipad-iphone.

Accordingly, I'm closing the issue as it appears unrelated to Smooth Scroll. Sorry it took me so  long to look at this!

**Comment by AnnaKosolapova** [comment]
Thank you for looking at that, but hey, I don't zoom anything there, actually

**Comment by cferdinandi** [comment]
You don't, but if you click on the search box, iOS itself zoom into the field.

**Comment by AnnaKosolapova** [comment]
Alrighty, got ya! Will try to somehow prevent page from zooming if it's even possible (because real example is not actually zooming, as it's fully responsive). Thanks for you help. Really appreciate it!

**Comment by cferdinandi** [comment]
No worries. Just an annoying iOS "quirk/bug" related to CSS. There may be a way around it, but I'm not sure what. Sorry!

**Comment by AnnaKosolapova** [comment]
Nah, that's totally ok, and really good to know the actual source of a problem. Will try to play around with it.
