### ISSUE TITLE
Footer height with js

### ISSUE THREAD

**Issue by Christo44** [cferdinandi/smooth-scroll#296]
Hi, 

I've noticed that the plugin works great. However I'm setting my footer height like so:

```js
var footerheight = $(".footer").height();
$("body").css("margin-bottom", footerheight);
if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
    $("body").css("margin-bottom", "0");
}
```

this causes the plugin to work links to other pages, but for links on same pages there is confusion. It simply ignores the data-header and offset attributes.  I tried using 'footerHeight' as the offset value too, but I'm not doing it right.

Should I be calling the smooth-scroll after I set the footer or how can I improve this ?

**Comment by cferdinandi** [comment]
Please provide a demo link: https://github.com/cferdinandi/smooth-scroll/blob/master/CONTRIBUTING.md#reporting-a-bug

**Comment by Christo44** [comment]
Can I share a private link with you ?

**Comment by cferdinandi** [comment]
Sure thing! You can email me at https://gomakethings.com/about
