### ISSUE TITLE
Function to run before scrolling

### ISSUE THREAD

**Issue by HectorLS** [cferdinandi/smooth-scroll#297]
Hi, the smooth-scroll has a callback function _// Function to run AFTER scrolling_
I was wondering if would be possible to add a funtion to run **BEFORE** 

Because in so many case, i have a mobile <nav> that fit the screen, and the <body> has the scroll locked when the <nav> is visible, so would be great to be able to unlock the <body> scroll before run **smoothScroll**

**Comment by cferdinandi** [comment]
No pre-run callback, but... you can use the Smooth Scroll API to do this yourself:

```js
// Listen for clicks
document.addEventListener( 'click', function (event) {
	
	// Don't run if right-click or command/control + click
	if ( event.button !== 0 || event.metaKey || event.ctrlKey ) return;

	// Check if a smooth scroll link was clicked
	// If using a selector other than [data-scroll], replace the .hasAttribute() check with classList.contains() or .id !== or whatever
	if ( !event.target || event.target.tagName.toLowerCase() !== 'a' || !event.target.hasAttribute( 'data-scroll' ) ) return;

	// Get target
	var anchor = document.querySelector( event.target.hash );
	if ( !anchor ) return;

	// Unlock scrolling

	// Scroll to the anchored content
	smoothScroll.animateScroll( anchor, event.target, {callback: function (){
		// Reenstate scroll lock
	}} );

}, false );
```

Personally, though, I'm not sure why you would prevent scrolling on mobile devices.

**Comment by cferdinandi** [comment]
I gave this a bit more thought, and I think a functional hook before animating actually is the right call here. I'll try to get this implemented in the next day or so.

**Comment by cferdinandi** [comment]
Added to v11 - currently in development and scheduled for release shortly.
