### ISSUE TITLE
TypeScript definition

### ISSUE THREAD

**Issue by TonyPythoneer** [cferdinandi/smooth-scroll#299]
Hello, @cferdinandi 

I very appreciate this repo. I want to add TypeScript definition for this definition.

But I encounter some issues, I want to discuss with you.

This repo hasn't a correctly npm link to point this. I can't contribute the definition of this repo on DefinitelyTyped, such as https://www.npmjs.com/package/smooth-scroll

I have two ideas to solve this:
  1. Rename this package name to `cferdinandi-smooth-scroll` and re-publish it on npm.
  2. Directly add definition in this repo.

How do you think?

**Comment by cferdinandi** [comment]
Sorry, not going to support this. This project lives exclusively on GitHub, and NPM, Browserify, and others will all let you install it directly from here.

I already spend considerable amounts of time managing this project and dozens of others. I'm not keen to add another step to the process.

**Comment by tony** [comment]
It doesn't hurt to at least welcome a pull request. They're just type definitions.

**Comment by cferdinandi** [comment]
@tony This package is actually now on NPM, per the docs.

However, this is disingenuous:

>  They're just type definitions.

Every package manager I support means additional tasks every time I update my plugin. And I manage several dozen, many of them very active, with regular updates and ongoing development.

**Comment by andreiho** [comment]
Types are now available: https://www.npmjs.com/package/@types/smooth-scroll

**Comment by janbiasi** [comment]
Appreciate your support @andreiho, at least in 2019 it would be essential to provide typings ...
