### ISSUE TITLE
Not working on firefox 

### ISSUE THREAD

**Issue by CRDD** [cferdinandi/smooth-scroll#304]
Smooth scroll works perfect on google chrome but in firefox it simply wont scroll down

if i scroll down a little bit and click one of the links it bumps me up to the top 

here is the site
http://pannaraitherapy.co.uk/new/

**Comment by cferdinandi** [comment]
The script does work in Firefox. It seems to be an issue with your site or implementation. (See the screen capture below).

I am seeing an error that you have not set an encoding type on your site. You're also loading a handful of other scripts. I would recommend removing them one-by-one to see if there's a conflict or something happening.

Unfortunately, though, I cannot provide specific site support for my open source projects. Best of luck!

![ff](https://cloud.githubusercontent.com/assets/1724852/21352664/85b033c0-c690-11e6-8b56-b269fd07e391.gif)
