### ISSUE TITLE
v10.2.1 not working when concatenated and uglified

### ISSUE THREAD

**Issue by operat** [cferdinandi/smooth-scroll#308]
After upgrading from v10.2.0 to v10.2.1 smooth-scroll stopped working in a couple of my projects. The console says: "TypeError: f.location is undefined".

I'm using a setup, where all JavaScript files are concatenated into one single file and this resulting file is uglified, all done by Grunt. v10.2.1 only works when I skip uglification.

smooth-scroll always worked correctly in that setup. Any ideas why it stopped with v10.2.1?

**Comment by cferdinandi** [comment]
Hi there. I just tested the minified version of Smooth Scroll, and it works as expected. I also tested concatentating this version with another file, and it still works as expected.

Accordingly, I suspect:

- Your minifier/uglifier is being overly aggressive/doing things wrong in how it minifies the file, or...
- There's a conflict with other files in your script.

Either way, I unfortunately cannot provide support for conflicts and issues with third-party scripts, plugins, and files. 

If you're curious, [here's what's new in v10.2.1](https://github.com/cferdinandi/smooth-scroll/blob/master/dist/js/smooth-scroll.js#L415-L422). I don't see anything there that should cause a minification issue.

**Comment by operat** [comment]
I looked at it again: the error persists. There are no conflicts with other scripts; I removed all other files to check, the error remained.

I found out however, that it works, when I use the normal, un-minified v10.2.1 and let Grunt do the Minification.

It's weird, that I never had any problems in that very setup with the minified versions up to v10.2.0. It's only since the step up to v10.2.1.

**Comment by cferdinandi** [comment]
Weird. I'm successfully using it, minified, on other projects.
