### ISSUE TITLE
Smooth scroll not work in Firefox & remove header id's

### ISSUE THREAD

**Issue by Alex-Sokolov** [cferdinandi/smooth-scroll#310]
We have a documentation with sidebar and content area.

If click anchor-link ("Использование компонентов") inside content-area — all ok, smooth scroll work
If click anchor-link ("Использование компонентов") in sidebar — no smooth scroll
After click link in sidebar — header id sometimes removed from tag

![2017-01-12 22 31 07](https://cloud.githubusercontent.com/assets/4497128/21905513/1c5e9fc6-d921-11e6-840d-a94caacda873.png)

- Think it is totally #305 but fix help only in content area
- Bug reproduced in Firefox (I'm testing on 50.1.0)
- If need own local copy of docs for test — https://github.com/translation-gang/ru.vuejs.org
- In my local copy I'm update smooth-scroll to v.10.2.1 (in repo: /themes/vue/source/js/smooth-scroll.min.js)
- Found that `clickHandler` remove header id

```js
// https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll.js#L484-L496

// Get the anchored element
anchor = document.querySelector( hash );

// If anchored element exists, save the ID as a data attribute and remove it (prevents scroll jump)
if ( !anchor ) return;
anchor.setAttribute( 'data-scroll-id', anchor.id );
anchor.id = '';

// If no hash change event will happen, fire manually
if ( toggle.hash === root.location.hash ) {
	event.preventDefault();
	hashChangeHandler();
}
```
Start look why `hashChangeHandler()` not called, where anchor id returned.

For example if we open page `http://localhost:4000/v2/guide/components.html#Что-такое-компоненты`
And click link to get to `http://localhost:4000/v2/guide/components.html#Использование-компонентов`

Inside `if ( toggle.hash === root.location.hash ) {`:
- toggle.hash = #Использование-компонентов
- root.location.hash = #Что-такое-компоненты

Hash event not fired, anchors are different! Smooth scroll remove header id and not doing something else.

Found possible fix:
```js
// Get the anchored element
anchor = document.querySelector( hash );

// If anchored element exists, save the ID as a data attribute and remove it (prevents scroll jump)
if ( !anchor ) return;
anchor.setAttribute( 'data-scroll-id', anchor.id );
anchor.id = '';

// If no hash change event will happen, fire manually
if ( toggle.hash === root.location.hash ) {
	event.preventDefault();
	hashChangeHandler();
} else {
	event.preventDefault();
	root.location.hash = toggle.hash;
}
```

After that all works, header id's will not delete and no scroll jumps.

**Comment by cferdinandi** [comment]
Hey, in order to even begin debugging this, I'll need a working, live (ie. on the web) demo running the latest version of Smooth Scroll.

**Comment by Alex-Sokolov** [comment]
Copy of out docs site with latest version: http://gbezyuk.ru:4000/v2/guide/components.html

**Comment by cferdinandi** [comment]
Your click even listener in `common.js` on line 177 is preventing the default link behavior and thus conflicting with Smooth Scroll. If you remove it, everything works as expected.

Closing this out as "won't fix," as I cannot provide support for third-party scripts.

**Comment by gbezyuk** [comment]
@cferdinandi thank you for your attention to this issue!
