### ISSUE TITLE
Remove selectorHeader from mobile

### ISSUE THREAD

**Issue by chandanndeep** [cferdinandi/smooth-scroll#314]
How I remove the below function from mobile layout

```js
<script>
    smoothScroll.init({
        selectorHeader: '[data-scroll-header]'
    });
</script>
```

**Comment by cferdinandi** [comment]
Right now there's no good way to do this with the API. I've been considering adding a way to dynamically get the header height on each click instead of once at the beginning, which would help, but for now... I'd check for viewport width on init, and again after a resize, and reinit if necessary.

Something like this:

```js
var breakpoint = 640; // Whatever your "mobile" cutoff is in pixels

// Setup our init as a function so we don't have to repeat ourselves
var initSmoothScroll = function () {
	// If <body> is wider than our breakpoint
	if ( window.getComputedStyle( document.body ).width < breakpoint ) {
		smoothScroll.init({
		    selectorHeader: '[data-scroll-header]'
		});
	} else { // otherwise...
		smoothScroll.init();
	}
}

// Init Smooth Scroll on page load
initSmoothScroll();

// Reinit Smooth Scroll on window resize
window.addEventListener('resize', initSmoothScroll, false);
```

**Comment by chandanndeep** [comment]
I use this code but it's stop smooth scroll on both window and mobile.

**Comment by cferdinandi** [comment]
That's because I forgot to convert the body width from a string into an integer. This should work:

```js
var breakpoint = 640; // Whatever your "mobile" cutoff is in pixels

// Setup our init as a function so we don't have to repeat ourselves
var initSmoothScroll = function () {
	// If <body> is wider than our breakpoint
	if ( parseInt( window.getComputedStyle( document.body ).width, 10 ) > breakpoint ) {
		smoothScroll.init({
		    selectorHeader: '[data-scroll-header]'
		});
	} else { // otherwise...
		smoothScroll.init();
	}
}

// Init Smooth Scroll on page load
initSmoothScroll();

// Reinit Smooth Scroll on window resize
window.addEventListener('resize', initSmoothScroll, false);
```

**Comment by chandanndeep** [comment]
Hi Chris Ferdinandi,

Thanks for fast reply. But same it's doesn't work for me.

Please see the site: http://sandbox.enservio.com/blank

**Comment by cferdinandi** [comment]
Can't get to your demo site. It's behind an auth screen.

**Comment by chandanndeep** [comment]
Any idea? How can i fix that issue.

Thanks

**Comment by cferdinandi** [comment]
Per the [contributing guidelines](https://github.com/cferdinandi/smooth-scroll/blob/master/CONTRIBUTING.md), can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)?

I'm afraid without one there's not much else I can do...
