### ISSUE TITLE
Add a setting to grab header height on each scroll, not just init

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/smooth-scroll#316]
Helps with headers that disappear on scroll.

**Comment by inspiredlabs** [comment]
Can we expect it to work with collapsable containers such as this? http://dev.bradsknutson.com/demos/css-accordion/

**Comment by cferdinandi** [comment]
I can't comment on compatibility with third party plugins, sorry! See https://github.com/cferdinandi/smooth-scroll/pull/318 for details, though.
