### ISSUE TITLE
failing to install

### ISSUE THREAD

**Issue by promptdev** [cferdinandi/smooth-scroll#317]
While working on a legacy project I was unable to install `cferdinandi/smooth-scroll` with `npm install`.
I searched for the package on [npm](https://www.npmjs.com/search?q=smooth-scroll) but couldn't find it.

Error I'm getting:

```
$ npm install
npm ERR! addLocal Could not install ../../cferdinandi/smooth-scroll@10.0.1
...
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
...
```

package.json

```
{
 ...
  "devDependencies": {
    ...
    "cferdinandi/smooth-scroll": "10.0.1"
  },
 ...
}
```

**Comment by cferdinandi** [comment]
The package isn't hosted on NPM, only GitHub.

You can still require it from a `package.json` file, but the way you do it is a bit different: http://stackoverflow.com/questions/23210437/npm-install-private-github-repositories-by-dependency-in-package-json
