### ISSUE TITLE
Use requestAnimationFrame when supported

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/smooth-scroll#333]

**Comment by desandro** [comment]
Here's the polyfill I use https://github.com/metafizzy/flickity/blob/v2.0.6/js/animate.js#L33-L47

**Comment by cferdinandi** [comment]
Thanks @desandro. I was thinking I'd use [the one from Paul Irish](https://gist.github.com/paulirish/1579671). Any reason you'd recommend yours over his?

**Comment by desandro** [comment]
Yeah, that one will work just fine. The version in Flickity is a slimmed down version of Paul Irish's script.

+ It's designed for 2017 browser support: IE10+, Android 4+, Safari 9+, iOS 9+, evergreen Chrome evergreen Firefox. You could remove `webkitRequestAnimationFrame` as its not needed anymore.
+ I don't use `cancelAnimationFrame` so it's removed

**Comment by zslabs** [comment]
I'd personally recommend not implementing a polyfill bundled in with your code and instead provide alternatives for users needing older browser support. I talk about about why I believe it's an issue to bundle polyfills in a [post I wrote](https://zslabs.com/articles/polyno/) a while ago.

**Comment by cferdinandi** [comment]
@zslabs I've been thinking through the best way to address this. My typical user base is a mix of both beginners who wouldn't know how to do something like that on their own, and advanced users who want as slim a code base as possible.

For me personally, I'll use multiple of my own plugins on some projects, and I'd rather have a single set of polyfills I load and share across plugins.

I may end up going with a two-tier model, similar to what [Bram Stein does with `fontFaceObserver()`](https://github.com/bramstein/fontfaceobserver). He provides a version with polyfills, and a version without (automated, I'm assuming, by his build tools).

**Comment by zslabs** [comment]
@cferdinandi Yeah, completely understand that - definitely a challenge of open-source with the varying experiences of your consumer-base. If you were to find it difficult to use a build tool to parse that out, mentioning the polyfill.io is a win-win in my mind 😉 since it really drives the point home of a copy/paste solution that seems to work for a lot of people out of the box.

**Comment by cferdinandi** [comment]
@zslabs I'd actually just heard of it the other day and was planning to experiment with it a bit.

The one thing I'm still trying to figure out (and this is a bit of a tangent) is if there's a way to preemptively get the browser info on my end *before* polyfill.io loads. They support serving a specific browser version if you send that info as a query string in the URL, and it would save a round trip that would delay JS loading time.

**Comment by zslabs** [comment]
Right. For what's it's worth, I believe they are using the Fastly service to determine the UserAgent and respond with the appropriate polyfills needed based on the other config sent to it, so I think if you were building an application that was to be used in only one browser (like IE7 haha) then you could specify it on request to save them from doing the actual lookup, but in all honesty, I have not experienced any noticeable regression in performance. When I worked on `digitalocean.com` it went so well for the marketing site, that the cloud team also integrated it into their dashboard.

**Comment by cferdinandi** [comment]
Strong endorsement! The other consideration: seems silly to send polyfills for a whole bunch of things when you may only be using one "needs a polyfill" method.

**Comment by zslabs** [comment]
Completely agree! The great thing about polyfill.io is you can leave it up to the user. If they want the default set to be checked with custom things not included by default, then they can do something like `https://cdn.polyfill.io/v2/polyfill.min.js?features=default,matchMedia`

Or, if they want ONLY a specific feature, `https://cdn.polyfill.io/v2/polyfill.min.js?features=matchMedia`

More to consider on their end than yours, but at the end of the day, allows you to not worry about polyfills anymore and have the end-user deal with those deficiencies (if any) depending on their needs while making for a smaller bundle-size on your end.

**Comment by cferdinandi** [comment]
Ok, so...

1. the more I play with it, the more I love polyfill.io
2. I just built a solution into my build tool that let's me dynamically create two versions: one with polyfills, and one without. 

Super easy to maintain, and now people will have options. I haven't applied it to this script yet, but I'll be ready as soon as it's time.

**Comment by zslabs** [comment]
🎉 Very cool. Excited to see that!

**Comment by cferdinandi** [comment]
Added to version 12 (coming soon)

**Comment by cferdinandi** [comment]
Done: https://github.com/cferdinandi/smooth-scroll/pull/362
