### ISSUE TITLE
No Stop Method?

### ISSUE THREAD

**Issue by felipearosemena** [cferdinandi/smooth-scroll#354]
I'm trying to make it so that if the user scrolls while `smoothScroll.animateScroll` is running, the smoothScroll is cancelled, otherwise the page seems to jank if you try to scroll as the method is being called.

Is there any way to cancel the smoothScroll effect? Something like `smoothScroll.stop()` would be nice.

**Comment by cferdinandi** [comment]
Duplicate: https://github.com/cferdinandi/smooth-scroll/issues/309
