### ISSUE TITLE
Destroy smoothScroll before scrolling is completed makes scrolling else where impossible

### ISSUE THREAD

**Issue by G-DEV21** [cferdinandi/smooth-scroll#356]
If page is scrolling to an anchor and "smoothScroll.destroy" is called, the page will be stuck at the anchor indefinitely, i.e. whenever a user scrolls away, page will always scroll back to the same anchor.

fiddle: https://jsfiddle.net/G_DEV/vgwpvnwj/

Fixed on PR: https://github.com/cferdinandi/smooth-scroll/pull/357

**Comment by cferdinandi** [comment]
Fix coming in v12

**Comment by cferdinandi** [comment]
Done: https://github.com/cferdinandi/smooth-scroll/pull/362
