### ISSUE TITLE
this is not a real issue

### ISSUE THREAD

**Issue by xiachaoxulu** [cferdinandi/smooth-scroll#359]
i am sorry , this is not a real issue。 i just give some tips：
if an  anchor has the id attribute，and CSS has applied the ID selector。
because you remove the id( although you buffer that)，cause the elements what applied the ID selector  lose all styles。 
cause, Splash screen and  root.PageYOffset  is inconsistent with the root.PageYOffset after the new style is applied（id attribute）

so， setTimeout（animateScroll，4） will be nice。

**Comment by xiachaoxulu** [comment]
I changed the ID selector to the class selector
= =！

**Comment by xiachaoxulu** [comment]
I changed the ID selector to the class selector
i think this is a bester solution. 
Would you consider writing this proposal in readme.md?

**Comment by cferdinandi** [comment]
Are you saying I should recommend people style with classes instead of IDs in the readme?

**Comment by xiachaoxulu** [comment]
yes

**Comment by xiachaoxulu** [comment]
Have I made myself clear about the reasons for doing so?

**Comment by cferdinandi** [comment]
yes

**Comment by cferdinandi** [comment]
Documentation to be updated explaining this in v12 (coming soon...)

**Comment by cferdinandi** [comment]
Done: https://github.com/cferdinandi/smooth-scroll/pull/362
