### ISSUE TITLE
Setting "offset" property on before

### ISSUE THREAD

**Issue by isaacalves** [cferdinandi/smooth-scroll#367]
Is it possible to have a dynamic ```offset``` property?

If I set ```offset``` property to be a function, it will be run only once, on initialisation (I would expect it to be run before each scroll so it would get an updated value).

When I assign the ```offset``` property to a variable and change its value on the ```before``` event callback, SmoothScroll will still use the old value assigned to it?

So, do I have to initialise SmoothScroll each time I want to do a scroll in order to do so?

**Comment by cferdinandi** [comment]
This is a big miss in the current setup. I'll flag this as a feature request with intent to support. No commitment on when I can get to this, but hopefully shouldn't be long.

**Comment by cferdinandi** [comment]
So, I'm looking at the code for this, and `offset` as a function runs right when the scroll begins, as The end location is calculated: https://github.com/cferdinandi/smooth-scroll/blob/master/dist/js/smooth-scroll.js#L328

It's *not* being run on initialization at all, but you don't have access to it via the callback.

Do you have a demo page or example of what you're trying to accomplish and cannot? I can take a look.

**Comment by adammockor** [comment]
It would be really helpful, if I could access `toggle` element to read `data-scroll-offset` attributes to get achieve functionality like this (different offsets for different screen widths):
```
<a href="#anchor" data-scroll data-scroll-offset="{ 320: 60, 768: 30}">Toggle</a>

<div id="anchor">...</div>
```

So I something like this or different API would be really nice:
```
new SmoothScroll('a[href*="#"]', {
  offset: (e) => e.srcElement.getAttribute('data-scroll-offset'),
});
```

**Comment by cferdinandi** [comment]
@adammockor That could be supported by passing in the `anchor` and `toggle` elements as variables into the function. I'd need to update my code as well, but it would allow you to do something like this:

```js
new SmoothScroll('a[href*="#"]', {
  offset: function (toggle) {
    return toggle.getAttribute('data-offset');
  }
});
````

**Comment by adammockor** [comment]
@cferdinandi yes that would be really nice. I can PR this if you want.

**Comment by cferdinandi** [comment]
@adammockor That would be great, thanks!

**Comment by cferdinandi** [comment]
[The latest release (v14.1.0)](https://github.com/cferdinandi/smooth-scroll/releases/tag/v14.1.0) passes the `anchor` and `toggle` elements into the `offset()` function, allowing you to customize the returned value based on what element was clicked or where you'll be scrolling to.
