### ISSUE TITLE
About URL issue

### ISSUE THREAD

**Issue by alisiddique** [cferdinandi/smooth-scroll#371]
Showing this url #smooth-scroll-top in every page. How can i fix this. I added go to top link with smooth scroll.

**Comment by cferdinandi** [comment]
Because of how Smooth Scroll works, it requires an ID. if you try to scroll to the top with only a `#` for the href, it will add an ID to scroll to. 

You can fix this by adding your own ID to the body element and using that in your Scroll to top link.
