### ISSUE TITLE
Doucment what attributes will be created

### ISSUE THREAD

**Issue by julmot** [cferdinandi/smooth-scroll#373]
I've noticed that the plugin creates `tabindex: -1` and `style` attributes on elements. I was wondering why this is necessary. Please document what this plugin does and why.

![2017-08-04 21_45_53](https://user-images.githubusercontent.com/8310677/28984506-8db579b4-795e-11e7-807f-b55708d02c97.png)

**Comment by cferdinandi** [comment]
1. `tabindex="-1"` let's `.focus()` be set on the `document` element when scrolling to the top, since it's not a normally focusable element.
2. The style attributes prevent the default outline behavior on focused elements from showing up on the entire document.
