### ISSUE TITLE
Always scrolling top

### ISSUE THREAD

**Issue by TiagoSousa26** [cferdinandi/smooth-scroll#376]
Hello

I am doing the migration to version 12 and with the changes, it always does scroll to the top. I have the following code
`import smoothScroll from 'smooth-scroll';
...
this.smoothScroll = new smoothScroll('a[href^="#linkto"]', {easing: 'linear'});
...
// when clicking on the link
let target = document.querySelector(element);
this.smoothScroll.animateScroll(target, 0, { offset: this.history.offsetTop + 10 });
`
And it scroll up. On the second click on the same link it gives this error `Cannot read property 'tagName' of null at Object.I.animateScroll`.

**Comment by cferdinandi** [comment]
Please provide a reduced test case: https://github.com/cferdinandi/smooth-scroll/blob/master/SUPPORT.md

I'll reopen once one is provided. Thanks.
