### ISSUE TITLE
Links always scroll to the top

### ISSUE THREAD

**Issue by llamicron** [cferdinandi/smooth-scroll#377]
Example: https://github.com/llamicron/smooth-scroll-bug
I have 2 sections in that example. One named "home" and one named "about". Clicking the link from "about" to "home" works fine, but "home" to "about" doesn't work. You can see that the url is correct, it's just not scrolling.

**Comment by cferdinandi** [comment]
Hi there. Can you please provide a [reduced use case](https://github.com/cferdinandi/smooth-scroll/blob/master/SUPPORT.md) for this issue? A reduced use case involves sharing the least possible code (including CSS) necessary to demonstrate the issue.

Thanks.

**Comment by othercodes** [comment]
Hi there I also having the same issue, here you have a demo site: with the issue https://goo.gl/pufqnD

- user: demo
- pass: demo2017

Click the blue button on slide

**Comment by cferdinandi** [comment]
@othercodes can you please provide an unobscured link to a trusted site (like JS Fiddle or CodePen), or to the source code as GitHub/Gist Repo?

Thanks!

**Comment by cferdinandi** [comment]
@suxiaogang The issue you're facing implies that you're not initializing the script correctly. That also seems like a separate issue from this one.

**Comment by llamicron** [comment]
@othercodes That looks like the same issue I'm facing. 

@cferdinandi I have improved my test case. It's at the same github link: https://github.com/llamicron/smooth-scroll-bug

I have also recorded a video of the bug in action: 
[[ https://gfycat.com/gifs/detail/HollowDrearyJapanesebeetle.gif | height = 300px ]]

**Comment by cferdinandi** [comment]
Hey everyone: looks like this may have been related to a bad calculation caused by some legacy code. I just pushed a PR for this. Does anyone want to test and confirm whether or not this fixes the issue?

https://github.com/cferdinandi/smooth-scroll/pull/378

@llamicron Thanks for the updated test case! This helped me isolate the issue. Cheers!

**Comment by llamicron** [comment]
@cferdinandi That seemed to fix it. 👍  Thanks for the quick fix.

**Comment by cferdinandi** [comment]
Awesome! Thanks for your help in getting this sorted out!
