### ISSUE TITLE
Bug smooth-scrool in firefox

### ISSUE THREAD

**Issue by halyson97** [cferdinandi/smooth-scroll#380]
The library gives an error when it clicks on some element that does not have a target for scrool.

![captura de tela de 2017-08-15 17-13-24](https://user-images.githubusercontent.com/9968866/29334472-e182ed10-81dd-11e7-9280-ac1d565ecece.png)

**Comment by halyson97** [comment]
The problem occurred using polymer # ^ 1.4 and firefox in version 54.0

**Comment by cferdinandi** [comment]
[Per the support guidelines](https://github.com/cferdinandi/smooth-scroll/blob/master/SUPPORT.md), please provide a reduced test case:

> - Clearly demonstrate the bug or issue.
> - Include the bare minimum HTML, CSS, and JavaScript required to demonstrate the bug.
> - A link to your production site is not a reduced test case.

Closing this issue for now. Will reopen once updated with a link to a reduced test case.
