### ISSUE TITLE
v12.1.4 publication on npm

### ISSUE THREAD

**Issue by skyksandr** [cferdinandi/smooth-scroll#384]
Could you please publish latest release with `endLocation` fix on npm?

**Comment by cferdinandi** [comment]
Once I merge it into the core, yes. Currently still just a PR.

**Comment by skyksandr** [comment]
Don't know, am I miss something?
This PR already merged https://github.com/cferdinandi/smooth-scroll/pull/378

**Comment by cferdinandi** [comment]
Nope. I'm an idiot. I forgot to update the tag and push to NPM. I thought you were referring to something else.

Done. Sorry about that!

**Comment by skyksandr** [comment]
Thank you Chris for such a quick help!

**Comment by cferdinandi** [comment]
Happy to help! 😄
