### ISSUE TITLE
Fixed header offsets

### ISSUE THREAD

**Issue by longo12** [cferdinandi/smooth-scroll#386]
Hi, firstly thanks for taking the time to develop this. 
I have two fixed headers, desktop at 120px high and mobile at 80px high when viewed at certain width, I can set the offset to 120 which then scrolls to the correct places in desktop, the problem is the 80px mobile does not.
I then read that the header feature will automatically offset scroll distances by the header height so thought this would solve my problem but I'm having trouble getting it to work, I'm changing this  header: null, to this, header: header in the actual library itself, but nothing then works. As far as I'm aware header is a valid CSS selector so any advice would be appreciated

**Comment by cferdinandi** [comment]
Two different headers, or a header that changes size based on viewport?

Smooth Scroll grabs the first matching selector in the DOM, so if you've got two separate headers, it won't work. The script literally won't support that sort of thing.

**Comment by robjtede** [comment]
I have a fixed header that changes height when the page is scrolled down. Thought there might be a dynamic way of calculating the offset but came to nothing. It would literally require the script to measure the header size and recalculate the end location on every frame.

**Comment by DavidOliver** [comment]
@longo12, aside from the issue of having two headers, I think it would need to be `header: 'header'` (with quotes) to make the selector a string.

To account for having two headers, perhaps you could use the `offset` config option (see readme), and give it a function that measures the height of the visible header element?

**Comment by robjtede** [comment]
@DavidOliver currently, the offset config option does not accept a function

**Comment by cferdinandi** [comment]
@robjtede It does in the current version: https://github.com/cferdinandi/smooth-scroll/blob/master/dist/js/smooth-scroll.js#L332

**Comment by robjtede** [comment]
@cferdinandi so it does, thanks for pointing that. My reference was the JSDoc for getEndLocation.

In which case, @DavidOliver's suggestion would work for situations where the header height does not change mid-scroll. It would work for @longo12 but not for my situation.

**Comment by strarsis** [comment]
@robjtede: What about using a `MutationObserver` for the header and just update the offset when it changes? This seems to be the most robust and elegant solution and it is well supported now including polyfills.

**Comment by robjtede** [comment]
@strarsis Because the end location (accounting for offset) is only calculated once, at the beginning of the scroll sequence.

**Comment by cferdinandi** [comment]
[The latest release (v14.1.0)](https://github.com/cferdinandi/smooth-scroll/releases/tag/v14.1.0) passes the `anchor` and `toggle` elements into the `offset()` function, allowing you to customize the returned value based on what element was clicked or where you'll be scrolling to.

This should give you what you need to better handle this.
