### ISSUE TITLE
Examples for valid data-scroll-ignore values

### ISSUE THREAD

**Issue by ellenkorbes** [cferdinandi/smooth-scroll#387]
Hi,

Is it possible to have some examples for valid data-scroll-ignore values provided? I've tried putting a bunch of different things there and nothing seems to work.

My plan is to initialize SmoothScroll twice, once for everything and ignoring one specific element, and then the second time doing the opposite. Not sure that's possible either.

Thanks :)

**Comment by cferdinandi** [comment]
Hey, I'll take a look at this soon. 🙂

**Comment by ellenkorbes** [comment]
Oh, sorry, I already figured it. Thanks :)
