### ISSUE TITLE
Remove the #tag from the url after the animation completes

### ISSUE THREAD

**Issue by abbassiddiqi** [cferdinandi/smooth-scroll#388]
Can you add support or an option to remove the #idname from the url after the animation is complete?

For example if on freshly loaded page, when I click on a link `http://mywebsite.com#products`, after the scrolling is complete it should update the url in the browser back to `http://myswebsite.com`.

You can achieve this by running the following statement in the console.
```js
window.location.href = window.location.hostname; // removes the hashtag
```

**Comment by abbassiddiqi** [comment]
I wanted to remove the anchor tags altogether from the url,
So I achieved this using vanilla javascript as:
```js
const smoothScroll = SmoothScroll();
const $anchors = document.querySelectorAll('a[href="#firsttag"],a[href="#secondtag"]');
$anchors.forEach(function ($anchor) {
  $anchor.addEventListener('click', function (event) {
    event.preventDefault();
    const id = '#' + $anchor.href.split('#')[1];
    const $target = document.querySelector(id);
    smoothScroll.animateScroll( $target );
  });
});
```
It would be nice if there is an option in the plugin for not adding the anchor tag (#) in the url.

**Comment by cferdinandi** [comment]
Smooth Scroll is progressive enhancement for anchor links. Removing the had breaks browser forward and back button functionality. Won't support. 

Also, this can be handled with the API, per the Docs. See the extras under the reasons.

**Comment by abbassiddiqi** [comment]
Thanks @cferdinandi, I missed the extras from the documentation. That works.
