### ISSUE TITLE
Document height

### ISSUE THREAD

**Issue by sevikon** [cferdinandi/smooth-scroll#389]
Hi, 
scrolling down didn't work on my website (Document height was wrong calculated). I had to replace getDocumentHeight function from:
 >	var getDocumentHeight = function () {
		return parseInt(window.getComputedStyle(document.documentElement).height, 10);
	};

to:
> var getDocumentHeight = function () {
        return parseInt(Math.max(document.body.scrollHeight, document.documentElement.offsetHeight, document.documentElement.clientHeight, document.documentElement.scrollHeight, document.documentElement.offsetHeight), 10);
    };

and it is working now. I used solution from here:
https://stackoverflow.com/questions/1145850/how-to-get-height-of-entire-document-with-javascript
If you wish you can replace your function too. 
Best regards,
Konrad

**Comment by cferdinandi** [comment]
Duplicate. https://github.com/cferdinandi/smooth-scroll/pull/385

Merging soon.
