### ISSUE TITLE
animateScroll() won't scroll down for integers

### ISSUE THREAD

**Issue by irisSchaffer** [cferdinandi/smooth-scroll#390]
Version: 12.1.4

When trying to use

```
    const smoothScroll = new SmoothScroll()
    smoothScroll.animateScroll(1000)
```

everything works fine when I am *below* 1000px and smooth scroll smoothly scrolls me up to 1000. If I am however, in the beginning of the page (or anywhere *above* the defined integer), smooth scroll doesn't do anything.

If I provide a node to scroll to, it doesn't smoothly scroll to it, but rather jumps to it if we are above the node. As soon as I'm below the element, it scrolls smoothly again.

**Comment by cferdinandi** [comment]
I suspect it may have been related to this issue: https://github.com/cferdinandi/smooth-scroll/pull/385

Would you mind downloading the latest version (12.1.5) and seeing if that fixes the issue?

**Comment by irisSchaffer** [comment]
It did indeed! Thanks for the help! :)
