### ISSUE TITLE
Not work in Safari Version 11.0 (12604.1.38.1.7)

### ISSUE THREAD

**Issue by exdeniz** [cferdinandi/smooth-scroll#392]
Scroll not work in Safari Version 11.0 (12604.1.38.1.7)
and no console error

**Comment by cferdinandi** [comment]
Working in Safari 11 for me. It's possible you have "Reduce Motion" enabled under System Preferences > Accessibility > Display.

Right now, only Safari supports this feature, but when enabled, animation is disabled as it can be jarring to people who suffer from motion sickness.

**Comment by exdeniz** [comment]
Reduce Motion, oh! I would never have thought of this feature.  Thanks.
