### ISSUE TITLE
Does not trigger the target pseudo class

### ISSUE THREAD

**Issue by loominade** [cferdinandi/smooth-scroll#393]
usually, on clicking an anchor link the targeted element can receive a special styling using the `:target` pseudo class. See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:target). When using smooth scroll this does not longer work:

Here is a fiddle
[https://jsfiddle.net/5oyLj9qt/1/](https://jsfiddle.net/5oyLj9qt/1/)

uncomment the first line of js to observe the desire behaviour.

**Comment by cferdinandi** [comment]
I should update the docs to reflect that this is a known issue, unfixable with JavaScript. See https://github.com/cferdinandi/smooth-scroll/issues/263.

Sorry :(
