### ISSUE TITLE
README: avoid unintended `#smooth-scroll-top` scrolls

### ISSUE THREAD

**Issue by lkraav** [cferdinandi/smooth-scroll#396]
In the WordPress world, occasionally external plugins have admin menu items with `#` anchors, which will trigger unintended smooth scrolling if we blindly follow README.md. I would recommend adding an example for ignoring links that are exactly `#`, and explicitly recommend against using such an anonymous target as a scroll to top mechanism. Then the default example configuration could become:

```html
<script>
	var scroll = new SmoothScroll('a[href^="#"]', ignore: 'a[href="#"]');
</script>
```

Wasn't able to think of a selector that would do this in a single expression.

Your thoughts?

**Comment by cferdinandi** [comment]
I've added a setting option for this in v14.x, currently in testing and awaiting release.

```js
{
    topOnEmptyHash: true, // If true, scroll to the top of the document on `href="#"`
}
```
