### ISSUE TITLE
Trigger before callback before calculating offset

### ISSUE THREAD

**Issue by simonpeters** [cferdinandi/smooth-scroll#397]
I wanted to use the before callback to calculate my offset dynamically, but the offset function gets called before the before callback.

Would make more sense if before is called first.

**Comment by cferdinandi** [comment]
The callback wouldn't be able to help you there (it doesn't give you access to that variable), but I am planning a rewrite that should help here.

**Comment by cferdinandi** [comment]
I'm flagging this is a duplicate of https://github.com/cferdinandi/smooth-scroll/issues/367, which I'll address in a feature release soon.
