### ISSUE TITLE
Need help getting it work in React

### ISSUE THREAD

**Issue by ziyafenn** [cferdinandi/smooth-scroll#399]
Hi guys! So far i've managed to import the js file into page and add ID's to links.
But still can't get it to work with the last step, adding the `var scroll = new SmoothScroll('a[href*="#"]');`

Can you guys help me to set it up correctly in React JS? 

Thanks in advance!

**Comment by cferdinandi** [comment]
I'd need to see a demo link to understand what's not working/why.

**Comment by cferdinandi** [comment]
Does the div you want to scroll to have an id of `id`?

```html
<div id="id"></div>
```

**Comment by ziyafenn** [comment]
@cferdinandi yes of course. See my previous message. I just don't know where and how to add
`var scroll = new SmoothScroll('a[href*="#"]');`

**Comment by cferdinandi** [comment]
Ah. Anywhere after you've loaded/imported `smooth-scroll.js`. Header, footer, doesn't matter.

**Comment by ziyafenn** [comment]
Don't know if you've used react, i'm doing it so 
```
    componentDidMount () {
        const script = document.createElement("script");

        script.src = "../utils/scroll.js";
        script.async = true;

        document.body.appendChild(script);
    }
```

and in console/network i don't see it loading.

**Comment by cferdinandi** [comment]
Without a working demo I can look at, I'm afraid I've reached the limit of the debugging I can help you with. Let me know if/when you get something setup that I can look at.

**Comment by cferdinandi** [comment]
BTW, this may help you out? https://stackoverflow.com/a/42848407/1293256

**Comment by ziyafenn** [comment]
Alright, i was using gatsby and managed to fix it by adding each script as a separate file. Thanks!
