### ISSUE TITLE
Smartphones ... !?

### ISSUE THREAD

**Issue by joopvos** [cferdinandi/smooth-scroll#400]
On iPhone 6s Plus no luck ... all browsers on MBP okay ... !?

```
<html>
<body>
<div id="top"></div>
…
<a data-scroll href="#top">Naar boven!</a> 
…
<!-- Smooth Scroll > https://github.com/cferdinandi/smooth-scroll -->
<script src="<txp:site_url />js/smooth-scroll.min.js"></script>
<script>
var scroll = new SmoothScroll('a[href*="#"]', {
// Selectors
ignore: '[data-scroll-ignore]', // Selector for links to ignore (must be a valid CSS selector)
header: null, // Selector for fixed headers (must be a valid CSS selector)

// Speed & Easing
speed: 500, // Integer. How fast to complete the scroll in milliseconds
offset: 0, // Integer or Function returning an integer. How far to offset the scrolling anchor location in pixels
easing: 'easeInOutCubic', // Easing pattern to use
customEasing: function (time) {}, // Function. Custom easing pattern

// Callback API
before: function () {}, // Callback to run before scroll
after: function () {} // Callback to run after scroll
});
</script>
</body>
</html>
```

**Comment by cferdinandi** [comment]
Works as expected on my iPhone (iPhone 6 on iOS10). Been using it for years.

Per the docs, reduced test case please: https://github.com/cferdinandi/smooth-scroll/blob/master/SUPPORT.md

**Comment by joopvos** [comment]
Chris, before I make my own test case ... your demo isn't working either on iPhone 6s Plus, iOS 11.2.1 ... all browsers. Does this help to locate the issue?

**Comment by cferdinandi** [comment]
Just tested that device/OS combo using BrowserStack, and it's working as expected. 

Do you by chance have "reduced motion" enabled on your device? If so, Smooth Scroll [respects user preferences and won't animate](https://github.com/cferdinandi/smooth-scroll#new-features).

> Smooth Scroll now supports Reduced Motion (currently a Safari-only feature). If the visitor has indicated that they [prefer reduced motion](https://css-tricks.com/smooth-scrolling-accessibility/), Smooth Scroll will jump to the anchor link as normal instead of animating the scroll.

**Comment by joopvos** [comment]
> Do you by chance have "reduced motion" enabled on your device? 

Oops, yes I have ... :o ... sorry and thanks Chris!

**Comment by cferdinandi** [comment]
All good! Glad we got it figured out. =)
