### ISSUE TITLE
Settings when Scrolling without updating the URL

### ISSUE THREAD

**Issue by kingmauro** [cferdinandi/smooth-scroll#403]
I'm trying scrolling without updating the URL. It works for me but I don't know how I could add an option to the function / ignore: 'a[href*="#carouselExampleIndicators"]' / 
Any help would be appreciated.

**Comment by cferdinandi** [comment]
v14.x, currently in testing and awaiting deployment, will include an option to disable URL updates while maintaining all other feature. This will let you use the default `ignore` setting out of the box.
