### ISSUE TITLE
Bootstrap - Modal focus() issue

### ISSUE THREAD

**Issue by rikkilake** [cferdinandi/smooth-scroll#404]
Hey,

Using v12.1.5.

Found a conflict between smooth-scroll and latest Bootstrap (currently 4.0.0beta3) - although likelihood is that conflict has been in place since BS3.

I have a modal with an input element inside it and a submit element, when the modal is opened the input field should gain focus using the recommended BS javascript method also shown below.

When smooth-scroll is active the field does NOT gain the focus, when I make smooth-scroll inactive the field correctly gains the focus proving the javascript snippet is not at fault.

`	<div class="modal" role="dialog" id="searchmodal">

		<div class="modal-dialog mx-auto" role="document">
			<div class="modal-content">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<form method="GET" action="/search">
					<div class="container modal-body">
						<div class="row no-gutters">
							<div class="col-12 col-md-9">
								<input tabindex="1" type="text" name="q" class="form-control" id="searchKeywords" placeholder="Tell us what you are looking for..." required minlength="3">
							</div>
							<div class="col-12 col-md-3 pl-0 pl-md-3 pt-3 pt-md-0">
								<input type="submit" class="btn btn-success btn-block" value="Search">
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<script type="application/javascript">
		// Every time a bs modal is shown, if it has an autofocus element, focus on it.
		$('.modal').on('shown.bs.modal', function() {
		  $(this).find('#searchKeywords').focus();
		});
	</script>`

**Comment by cferdinandi** [comment]
Demo/reduced test case please.

**Comment by cferdinandi** [comment]
Closed due to nonresponse.
