### ISSUE TITLE
Feature Discussion: Scroll to bottom is element is near bottom

### ISSUE THREAD

**Issue by robjtede** [cferdinandi/smooth-scroll#405]
When an element is too close to the bottom of the page for scrolling to place it at the top, there is a sudden stop when the page hits the bottom. There could be an option to scroll to the bottom if the element to be scrolled to is in this region.

Something in the config object like `{ clipToBottom: true }`.

I'd be willing to create a PR if this sounds like a reasonable feature.

**Comment by cferdinandi** [comment]
Hey @robjtede - first off, THANK YOU for such a well formed issue/feature request. This is super helpful!

Now the nitty gritty: how might this behavior differ from the default?

**Comment by robjtede** [comment]
It would simply provide a nicer experience to cover the edge case where an element cannot be scrolled to entirely.

**Comment by cferdinandi** [comment]
Forgive me for being dense, but what *exactly* would the behavior look like? How would the scrolling animation differ from what it does today?

**Comment by robjtede** [comment]
Red: what it's trying to to
Blue: what happens
Purple: what i'm suggesting be an option

![capture](https://user-images.githubusercontent.com/3316789/35623750-96d49e7c-0684-11e8-96a6-e74146dbc4d2.PNG)

**Comment by cferdinandi** [comment]
Ah ok, so you want to, if the scrolling will be cut short because you'll reach the end of the page, calculate the distance based on stopping at the bottom to provide a smoother animation?

If so, yes, I'm 100% in favor of this.

**Comment by cferdinandi** [comment]
I would also make doing this the default behavior.

**Comment by robjtede** [comment]
Yes, that's what I'd like to see.

**Comment by cferdinandi** [comment]
Fixed: https://github.com/cferdinandi/smooth-scroll/releases/tag/v14.2.0
