### ISSUE TITLE
Custom bezier problems

### ISSUE THREAD

**Issue by tr1s** [cferdinandi/smooth-scroll#408]
What exactly am I supposed to put in the custom bezier section?

`customEasing: function (time) {cubic-bezier(.15,.82,.54,.85)}, // Function. Custom easing pattern`

I tried this and without the cubic-bezier part, but it breaks. Could you please provide an example?

Thanks!

**Comment by cferdinandi** [comment]
I need to improve the documentation there!

You'd do something like this:

```js
var scroll = new SmoothScroll('a[href*="#"]', {
	customEasing: function (time) {

		// return <your formulate with time as a multiplier>

		// easeInOut Quad
		// acceleration until halfway, then deceleration
		time < 0.5 ? 2 * time * time : -1 + (4 - 2 * time) * time;

	}, // Function. Custom easing pattern
});
```

You passed in a CSS easing pattern. Here's what some of the included patterns look like:

```js
// easeOut Quart
// decelerating to zero velocity
1 + (--time) * time * time * time * time;

// easeInOut Quad
// acceleration until halfway, then deceleration
time < 0.5 ? 2 * time * time : -1 + (4 - 2 * time) * time;
```

Unfortunately, the math behind these sorts of animations is beyond me, so I cannot help you translate what you've got into a JS function for the animation.
