### ISSUE TITLE
Offset function attributes

### ISSUE THREAD

**Issue by zipper** [cferdinandi/smooth-scroll#410]
When a function is used as `offset` parameter, it would be useful to know the clicked element (and potentially target element as well) inside this function. I want to dynamically change the offset based on clicked (actually target would be more appropriate) element and window width. Now the only way would be another instance of smooth scroll, but since there is only single link with that properties, it seems a bit overkill.

**Comment by cferdinandi** [comment]
Interesting... can you tell me a bit more about this use case? What information do you get from the clicked element (and target) that influence the offset?

Happy to entertain this, but I make every extra bit of code fight for its right to exist.

**Comment by zipper** [comment]
I guess it would be best with example: https://codepen.io/zipper/pen/LQywLy/

I have a layout similar to this one. There are some areas I want to be able to target. Some of them might have an image inside them and the image might (but not necessarily have to) overflow. When I scroll to that particular area, I want to offset the scroll so the image is fully visible when targeted. To make things harder, the navbar is sticky. And finally, the image negative offset changes through responsive.

If I can access the target element (or clicked, or both), I could handle all of this with just one instance of smooth scroll (using custom made `offset` function). Now I need to make new instance for every box. Or maybe am I missing something? I'm open for suggestion how to achieve this behaviour easier way. As I said multiple instances seems not ideal in this case. The now deprecated data attributes would be better, but they wouldn't help with responsive, since the offset changes.

One solution I was thinking about is wrapping the gray area and image into another div and target that. But since the areas actually may overlay each other, I don't think I could do that.

Thank you for help, appreciated.

**Comment by cferdinandi** [comment]
Ah, I see now! Because the images are pulled out of the content section, but only certain sections, the offset will vary.

Makes total sense. I can support this. Give me a little while to get it added, but happy to do so!

**Comment by zipper** [comment]
Thank you very much, will be looking forward for updated version :)

**Comment by cferdinandi** [comment]
[The latest release (v14.1.0)](https://github.com/cferdinandi/smooth-scroll/releases/tag/v14.1.0) passes the `anchor` and `toggle` elements into the `offset()` function, allowing you to customize the returned value based on what element was clicked or where you'll be scrolling to.

This should give you the info you need to handle use cases like the one referenced above.
