### ISSUE TITLE
Jumps when scrolling upwards

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/smooth-scroll#414]
For some anchor links smooth-scroll jumps directly to the element and just smoothly scrolls up a bit.

**Comment by cferdinandi** [comment]
I'll be doing a core rewrite that should address issues like this.

**Comment by basicdays** [comment]
Does the old `easeOut` method not work anymore? Tried changing to `easing: easeOutQuad` and it didn't seem to get around the issue.

**Comment by strarsis** [comment]
@cferdinandi: Is there a chance for updates in near future?

**Comment by cferdinandi** [comment]
v14.x is almost ready to deploy and should fix this. Will update soon!

**Comment by cferdinandi** [comment]
I just release v14, which I think should fix this. Would you mind testing and let me know?

**Comment by cferdinandi** [comment]
Closed due to inactivity. Will reopen if a reduced test case is provided.
