### ISSUE TITLE
Smooth scroll sometimes works and sometimes not

### ISSUE THREAD

**Issue by SilencerWeb** [cferdinandi/smooth-scroll#416]
Why does it sometimes work and sometimes not on my website? I tried to do same on codepen and it works fine!

I include smooth-scroll.js in vendor.js and init plugin in scripts.js when DOM is ready.

Initialization:
```js
new SmoothScroll('a[href*="#"]', {
  speed: 1000,
});
```

[Website](http://silencer.website/stasyq_adaptive/) (first 2 links: team and faq)
[Codepen](https://codepen.io/SilencerWeb/pen/PQvByO)

**Comment by cferdinandi** [comment]
By way of etiquette, you should let people know that a link is porn. Not cool. 

I can't provide debugging for specific sites here (that's a paid offering), but you might start by creating a reduced use case. Remove as much as you can from the site in the way of scripts and styles until the problem goes away. I suspect there's a conflict with some other code happening.
