### ISSUE TITLE
IE11: Smooth Scroll with sticky header not working

### ISSUE THREAD

**Issue by tsega** [cferdinandi/smooth-scroll#417]
I have tried on Chrome, Safari and Firefox the Smoot Scroll effect works properly but on IE11 it's not. I am using edge version. I read in the [Know Issues]() section that having a `body { height: 100%;}` interferes with height calculation but this seems not to be a problem in my case as it works just fine on all other browsers.

Additionally, it's not only the position that is off but also the animation or lack there of. Any pointers here?

**Comment by omar-abdul** [comment]
`<script src='js/smooth-scroll.polyfills.min.js' type="text/javascript">`  made it work for me on IE11 and also make sure js is enabled. 
I think IE 11 doesn't utilize `<body onscroll='stickynav()'>`  very well but when i called `window.onscroll()` from my js file it worked as expected

**Comment by cferdinandi** [comment]
Reduced test case please.

**Comment by cferdinandi** [comment]
Closed due to inactivity
