### ISSUE TITLE
cancelScroll API not working

### ISSUE THREAD

**Issue by ivanvillacreative** [cferdinandi/smooth-scroll#424]
Im trying to use the cancelScroll API but it is not responding. Here is a sample code that I feel should work 

```
// smooth Scroll arrows ---
var scrollArrow = new SmoothScroll("[data-scroll]", {
   speed: 10000
  });

  $('.home-product').on('click', function(){
    console.log("should cancel scroll");
    scrollArrow.cancelScroll();
  });
 ```

**Comment by cferdinandi** [comment]
Reduced test case please: https://css-tricks.com/reduced-test-cases/

**Comment by ivanvillacreative** [comment]
Sorry about that, Thanks for the tip though I will start doing reduced test case for every new bug.

**Comment by cferdinandi** [comment]
No worries, and good news! I just pushed v14.0.0, which fixes this issue.

There is [one other small bug](https://github.com/cferdinandi/smooth-scroll/issues/430) in this major version release that needs addressing. I'll be fixing that one tomorrow.
