### ISSUE TITLE
Using with ES6

### ISSUE THREAD

**Issue by sroberson** [cferdinandi/smooth-scroll#440]
I'm trying to use this in an ES6 environment using webpack:

```
import SmoothScroll from "vendor/smooth-scroll/smooth-scroll.js";
const scroll = new SmoothScroll("[data-scroll]", { offset: "70" });
```
or

```
import * as SmoothScroll from "vendor/smooth-scroll/smooth-scroll.js";
const scroll = new SmoothScroll("[data-scroll]", { offset: "70" });
```

But when I do this I'm getting the error:

```
Module not found: Error: Can't resolve 'vendor/smooth-scroll/smooth-scroll.js' in '/Users/me/Documents/projects/MyProject/ui/js'
```

These paths are correct, but I don't know how to get around this.  

I tried using your ES6 example with

```
import("vendor/smooth-scroll/smooth-scroll.js")
  .then(function () {
    new SmoothScroll("a[href*=\"#\"]"); 
  });
```

But I then get the error of `Parsing error: Unexpected token (`
as it looks like it doesn't like the parenthesis.

I also tried:

```
import ("vendor/smooth-scroll/smooth-scroll.js")
  .then(function () {
    new SmoothScroll("a[href*=\"#\"]"); // eslint-disable-line
  });
```

but get the same error.

I also tried all of the above with the `smooth-scroll.polyfills.js` version.

**Comment by cferdinandi** [comment]
I can't speak to Webpack, as I don't use it. *But...*

Smooth Scroll doesn't use `export`'s. The Common JS wrapper included in the UMD structure it uses allows you to use native ES6 modules with *dynamic imports* only.

As you've discovered, neither of these will work:

```js
import SmoothScroll from "vendor/smooth-scroll/smooth-scroll.js";
const scroll = new SmoothScroll("[data-scroll]", { offset: "70" });

// or...

import * as SmoothScroll from "vendor/smooth-scroll/smooth-scroll.js";
const scroll = new SmoothScroll("[data-scroll]", { offset: "70" });
```

However, this method *will* work natively:

```js
import("vendor/smooth-scroll/smooth-scroll.js")
  .then(function () {
    new SmoothScroll("a[href*=\"#\"]"); 
  });
```

You can see it in action by [visiting the demo page](https://cferdinandi.github.io/smooth-scroll/), opening the console tab in developer tools, and pasting this in and running it.

```js
import ("https://cferdinandi.github.io/smooth-scroll/dist/smooth-scroll.js")
  .then(function () {
    new SmoothScroll("a[href*=\"#\"]"); // eslint-disable-line
	console.log('resolved!');
  });
```

If I had to guess, Webpack is choking on the dynamic import. This section in their docs may help you, but I know nothing about Webpack, so I'm grasping at straws here: https://webpack.js.org/guides/code-splitting/#dynamic-imports

**Comment by soumyanjaleemahapatra** [comment]
Hi! I am having issues instantiating SmoothScroll() after transpiling import() using dynamic-import-node plugin by Babel. I get the error SmoothScroll is not a constructor. I am using the following code:
import ('vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js')
  .then(function() {
    new SmoothScroll('a[href*="#"]');
  });

Kindly suggest if I am doing something wrong.

**Comment by Harti** [comment]
@cferdinandi certain asset pipelines won't even let you compile this, as previously mentioned.
(I, personally, am using TypeScript which has been gaining a lot of traction lately.)

Granted, it's not just your library that suffers from this kind of issue.

Granted, there is a workaround where you can inline the code you used, that's working for *you*, in *your* setup.

Calling it "natively supported" is dangerous:
![image](https://user-images.githubusercontent.com/2056108/44038390-f5db9f62-9f16-11e8-9b7f-b64ab77faac4.png)
This is by no means good enough for production. This is why so many people (myself included) rely on Webpack, TypeScript and the likes. It's a hassle for all of us, believe me, but ignorance doesn't make things right.

Just a heads up: Any dumpster library will prevail over `smooth-scroll` provided it has ES6 module export.

**Comment by designrubenz** [comment]
I stumbled upon this thread when trying to make smooth-scroll work with webpack 4.
@sroberson's 
``` 
import SmoothScroll from "vendor/smooth-scroll/smooth-scroll.js";
const scroll = new SmoothScroll("[data-scroll]");
```
in my main-entry-file works perfectly.

**Comment by Harti** [comment]
@designrubenz you’re not using TypeScript then, I assume?

**Comment by designrubenz** [comment]
true, @Harti, and sorry I didn't realize that this was issue you were talking about.

**Comment by cferdinandi** [comment]
> Just a heads up: Any dumpster library will prevail over smooth-scroll provided it has ES6 module export.

🤔

**Comment by cferdinandi** [comment]
I would love to figure out an easy way to support UMD and ES6 exports properly.
