### ISSUE TITLE
Demos are too quick

### ISSUE THREAD

**Issue by FranciscoG** [cferdinandi/smooth-scroll#442]
love the lib, great work!  

just a minor minor critique.  Your demo page transitions are a bit too fast.  IMHO they don't show off the easing as well as they could be.  One small suggestion would be to slow speed down to 1500ms.  That way you can really see the Easing happen

I created a Codepen demo so you can see how it looks slowed down a bit https://codepen.io/FranciscoG/pen/ERwWqg

Maybe I'll take a stab at editing the demo page and put in a pull request.  Would like to add the ability to select which easing you want to use and change the options as well.  

edit: wording.  Trying not to sound snarky.  again, thanks for this library, it's great!

**Comment by cferdinandi** [comment]
I totally understand what you're saying, but... I'm worried that people will think the script runs animations really slowly if I do this.
