### ISSUE TITLE
First anchor click doesn't scroll smooth

### ISSUE THREAD

**Issue by Bigblock** [cferdinandi/smooth-scroll#444]
I have a problem i can reproduce in any browser.

I have a navigation and i have anchor points.

If i reload the website and click directly on an anchor so the anchor moves to the top, only the fist time the anchor doesn't scroll. After that everything behaves live it should.

If you want you can test it here: https://986fans.de/

For example scoll down and click on "BEISPIELE SCHÄDEN" when its in the middle of the screen (from top and bottom) to move it to the top.

If you have questions about the issue, please let me know.

Thanks

**Comment by cferdinandi** [comment]
I'm actually unable to see that happening on my end. Hmmm...

**Comment by Bigblock** [comment]
Hi, thanks for your feedback. I've made a video. You can see the effect at 0:05 when i click on the anchor "FAQ / GENERELLE HINWEISE" the side doesn't scroll:

https://youtu.be/ClB5YppLsAs

If i click the second time, the page scrolls smoothely.

To get this effect, the browser cache needs to be empty.

Let me know if you need some more infos or how i can help to solve the problem.

Thank you!

**Comment by Bigblock** [comment]
OK, did some more research.

If the URL in the browser says https://986fans.de/ and i click on an anchor, the site doesn't scroll smooth to that anchor the first time i click on that anchor.

If the URL in the browser says https://986fans.de/index.html and i click on an anchor, the site scrolls smoothely to the anchor i have clicked on.

So it maybe the problem is that the browser doesn't know where he is if there is no index.html appendix. Sorry, hard to describe. English is not my mother language. ;)

Thanks and regards

**Comment by Bigblock** [comment]
OK, solved the problem by renaming the anchors from
<a href="./index.html#anchornumber">anchorname</a
to
<a href="#anchornumber">anchorname</a>.

Now everything works fine.

**Comment by cferdinandi** [comment]
Aha! Glad you got it figured out. 😀
