### ISSUE TITLE
Element.scrollIntoView

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/smooth-scroll#446]
Could this become a polyfill or extension of [`Element.scrollIntoView`](https://developer.mozilla.org/en/docs/Web/API/Element/scrollIntoView)?

**Comment by cferdinandi** [comment]
Support is so good for `Element.scrollIntoView()` at this point (IE8 and up for basic support, modern browsers, excluding Edge, for options) that I see this existing as more of library when you want more control.

The amount of code needed to polyfill Element.scrollIntoView() makes it not worth it, IMO, for how basic its features are.
