### ISSUE TITLE
Demo doesn't work in Safari 11.1.2

### ISSUE THREAD

**Issue by chengyin** [cferdinandi/smooth-scroll#447]
With the Demo in README, there is no animation at all in Safari. Chrome works.
Version 11.1.2 (13605.3.8)

https://cferdinandi.github.io/smooth-scroll

**Comment by cferdinandi** [comment]
Duplicate https://github.com/cferdinandi/smooth-scroll/search?q=safari&type=Issues

**Comment by chengyin** [comment]
My bad! Thanks.
