### ISSUE TITLE
Feature Request: isolate custom events to a specific instance of smooth-scroll 

### ISSUE THREAD

**Issue by megalofauna** [cferdinandi/smooth-scroll#448]
Love smooth-scroll! Is there a way to isolate the custom events --

```
scrollStart
scrollStop
scrollCancel
```

-- to specific instances of smooth-scroll? I'd like to have two separate instances of smooth-scroll with different behaviors for each, but haven't been able to make it happen.

If that's already possible (and I just don't know how to make it happen), sorry for the time waster. 

Thanks!

**Comment by cferdinandi** [comment]
Interesting use case!

I'm assuming the different instances have different selectors associated with them? If so, you could hook into `event.detail.toggle` in your event listener to achieve what you're trying to do.

The `event.detail.toggle` property is the element that triggered the scroll animation (ie. the link). You could possibly check if the appropriate selector is there and run different behaviors accordingly. 

Something like this...

```js
document.addEventListener('scrollStop', function (event) {

	if (event.detail.toggle.matches('.selector-1')) {
		// Do something...
	} else if (event.detail.toggle.matches('[data-some-other-selector]')) {
		// Do something else...
	}

}, false);
```

Would that work?

**Comment by megalofauna** [comment]
D'oh! Yes. That will work perfectly. Thanks, Chris!
