### ISSUE TITLE
Add the option to define the "scroll container" - not only document body

### ISSUE THREAD

**Issue by BrianLaughlan** [cferdinandi/smooth-scroll#449]
Firstly, great script, thank you! Hopefully you can find a few mins to review this. Any additional info you need, please let me know.

I believe this has been addressed in other issues, but from what I can see, none offered an actual use case, so I wanted to open a fresh issue with my example. 

It would be nice to include an option that would allow us to define a "scroll container". The current setup only works on the document "body".

Here is a standard (working) example with body scrolling: 
https://jsfiddle.net/29c1j6eq

Now here is the same example, except the scroll should not happen on the body, but on a container: 
https://jsfiddle.net/bzprs0ua

Look forward to hearing from you!

**Comment by BrianLaughlan** [comment]
Also, this be be of some use: https://gist.github.com/twxia/bb20843c495a49644be6ea3804c0d775

**Comment by cferdinandi** [comment]
Duplicate: https://github.com/cferdinandi/smooth-scroll/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+container

**Comment by BrianLaughlan** [comment]
As mentioned .... "I believe this has been addressed in other issues". 

Anyway... so there is really no chance of anything like this ever being implemented?

**Comment by cferdinandi** [comment]
No, sorry. As mentioned in the other issues, doing this within parent containers requires a different approach that adds a lot more complexity and code to the script.

You might instead use the `scroll-behavior: smooth` CSS property: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
