### ISSUE TITLE
Scrolls To Top

### ISSUE THREAD

**Issue by ChrisStayte** [cferdinandi/smooth-scroll#450]
For some reason it keeps on scrolling to the top. Here is a link to the page and the repository
https://creation.cortain.com/about/
https://github.com/ChrisStayte/Cortain-Creation

It's what you click on "Our Philosophy, Mission, Vision" Tabs in the middle of the page.

**Comment by cferdinandi** [comment]
The tab script and Smooth Scroll are conflicting with each other.

At the time that SmoothScroll runs, the target `.tab-pane` has `display: none`. Smooth Scroll thinks it doesn't exist, and scrolls you to the top.

I couldn't find any JS controlling the tabs, though, so I'm not sure how to fix it.

**Comment by ChrisStayte** [comment]
This was an issue with integrating it with bootstrap. I changed it from href to anything else and functionality worked both on smooth scroll and bootstrap.
