### ISSUE TITLE
wrong URL with "updateURL: true," enabled

### ISSUE THREAD

**Issue by bennie99** [cferdinandi/smooth-scroll#452]
I use a CMS with "smooth scroll" intergrated and in js settings i have
updateURL: true,

The problem is that I use the language string as the first URL parameter (for example, http://example.com/en/).

With an anchor, the URL looks like http://example.com/en/#anchor.
But with the option "updateURL: true", which I like to use, the language string is kicked out and the URL looks like this: http://example.com/#anchor after an anchor link was clicked.
That's obviously the wrong URL.

If I use the "updateURL: false", it works, but I want to have the anchor in the URL.
How can I solve this problem?

**Comment by cferdinandi** [comment]
@bennie99 Do you have a reduced test case I can look at?

I have Smooth Scroll running with `updateURL: true` [on this site](https://vanillajsguides.com/complete-set/). If you click the `Start learning now →` button, you'll get scrolled down the page and the URL structure remains intact. I wonder if there's another script in your CMS that's hooked into `popstate` changes or something.

**Comment by bennie99** [comment]
No sorry, no test case It's a customer project in progress.

Yes `updateURL: true` works for me as well, but your example is a" normal "URL, so to speak.
That works fine here as well
As I have described, in my particular case I need the language string like http://example.com/de/#anchor.
In the source code of the website the link is ok.
If you click on it, it will scroll to the correct anchor, but the URL will change
`http: // example.com / # anchor`
The language string is gone 
No other JS - i've tested several cases.

**Comment by cferdinandi** [comment]
I don't get it. The URL you're describing is a "regular" URL, too. 

Sounds like there's something else going on behind the scenes.

Unfortunately, without a reduced test case there's not much I can do to help. If you can provide one, please feel free to open this issue back up.

**Comment by GuillaumeGBzh** [comment]
Hi @cferdinandi,

I have the same issue. 

I have : 
- a base URL in the <head> : `<base href="https://www.example.com" />`
- Some links with anchors like : `<a href="/test/#content1">Text</a>`

When i click on a link, the URL will change `https://www.example.com/#content1`.

Can you reopen this ticket please ?

**Comment by Sir-Genius** [comment]
+ 1. I have this issue too.

**Comment by cferdinandi** [comment]
All, I'm happy to reopen with a reduced test case. Unable to replicate on my end.

**Comment by ebro** [comment]
i had the same issu. 

I fixed it with following Code and Option updateURL: false:

`document.querySelectorAll('a[href*="#"]').forEach((el) => {
    el.addEventListener('click', (e) => {
        let clickedFullUrl = e.currentTarget.href;
        let clickedHash = clickedFullUrl.substring(clickedFullUrl.indexOf('#'));
        let clickedUrlPath = clickedFullUrl.replace(clickedHash, "");
        let currenturlPath = location.href.replace(location.hash, "");
        if (currenturlPath == clickedUrlPath) history.pushState('', '', clickedFullUrl);
    })
})`

updateURL seems only to update the hash from base URL. It ignores the Path from the URL.
