### ISSUE TITLE
When pageYOffset is not zero,the first time animate scrolling will got an error.

### ISSUE THREAD

**Issue by dingyi1993** [cferdinandi/smooth-scroll#457]
See the gif below.
Your demo on the readme can reproduce.
![98x08-3g8rv](https://user-images.githubusercontent.com/11729409/51614774-55021780-1f61-11e9-95f6-50993cd400bf.gif)

**Comment by cferdinandi** [comment]
Good catch! I'm on it!

**Comment by dingyi1993** [comment]
> Good catch! I'm on it!

I've resolved in #458
