### ISSUE TITLE
Exclude by parent class

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/smooth-scroll#460]
There is a slider that uses anchor links for its pagination.
The anchor links are contained by a list with a specific class (`.flex-control-nav`).

How can all anchor elements with an anchor in their `href` be selected except 
the anchor links contained by a parent element with the class `.flex-control-nav`?

```js
new SmoothScroll('*:not(.flex-control-nav) a[href*="#"]');
````
But this still selects all anchor elements on the page, including the ones used by the slider for pagination.

**Comment by cferdinandi** [comment]
Targeting with `:not()` can be a real pain. That's actually why [an `ignore` setting](https://github.com/cferdinandi/smooth-scroll#global-settings) now exists (I ran into a similar problem myself).

You would do something like this:

```js
new SmoothScroll('a[href*="#"]', {
    ignore: '.flex-control-nav a[href*="#"]'
});
```

You can pass in multiple selectors to ignore, comma separated, if needed.
