### ISSUE TITLE
e.charAt is not a function.

### ISSUE THREAD

**Issue by exdeniz** [cferdinandi/smooth-scroll#461]
On page without smooth-scroll selector periodically there is the bug:

```e.charAt is not a function. (In 'e.charAt(0)', 'e.charAt' is undefined)```
in 
```
	var escapeCharacters = function (id) {
		// Remove leading hash
		if (id.charAt(0) === '#') {
			id = id.substr(1);
		}
```
/node_modules/smooth-scroll/dist/smooth-scroll.polyfills.js:188:1

Bug seen on iOS12 in Safari. Bug detected sentry.io and and reproducing it locally failed.

**Comment by cferdinandi** [comment]
Can you provide any more details about the conditions in which this bug appears?

**Comment by exdeniz** [comment]
I myself can not catch it. I can show logs with sentry.
https://i.imgur.com/3RJh4if.png
https://i.imgur.com/g1ml02h.png
and site with error - https://malt.ru/oplata-i-dostavka/

**Comment by cferdinandi** [comment]
Clicking the offending link on the site provided, this appears to be an issue with a different script, not Smooth Scroll.

Since this cannot be replicated, I'm going to close the ticket. If you can create a reduced test case for it, happy to reopen.
