### ISSUE TITLE
Have to initialize twice

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/smooth-scroll#463]
For one particular page `smooth-scroll` has to be initialized twice 
(once when constructing, and again with `init(...)`) for having proper scroll targets:
```js
var scroll = new SmoothScroll(scrollSelector, scrollOpts);
                  scroll.init(scrollSelector, scrollOpts);
````
Otherwise `smooth-scroll` scrolls too far upwards or downwards or even to the top of page.
The incorrect offset also depends on the scroll position, when it already scrolled (incorrectly) to the target, 
going to that anchor again results in it moving around up and down even to the top of page.

After removing some elements inside the section to be addressed by anchor (ID), 
it appears that `smooth-scroll` incorrectly uses some height of elements inside for the (incorrect) offset.

**Comment by cferdinandi** [comment]
Reduced test case please?

**Comment by strarsis** [comment]
@cferdinandi: I try to isolate the responsible markup/styles and then I add a link to a test case.

**Comment by strarsis** [comment]
I am still trying to find the responsible markup/styles.
Interestingly, calling `init(...)` with the _header selector_, 
not with the options fixes the issue (but the options get lost) (related https://github.com/cferdinandi/smooth-scroll/issues/464), 
are the options passed to `init(...)` instead, the scroll is still off.

**Comment by cferdinandi** [comment]
Smooth Scroll self initializes when you instantiate it. You should not need to call `init()` ever unless you need to update your options later.

**Comment by cferdinandi** [comment]
Is this still an issue for you? The latest version of Smooth Scroll has removed `init()` as a public method.

**Comment by strarsis** [comment]
@cferdinandi: Right, `Uncaught TypeError: scroll.init is not a function`.
But now the scroll offets are also off again.

**Comment by cferdinandi** [comment]
That tracks, as `init()` was removed as a public API. But you shouldn't have to init again for them to work anyways.

It's possible Smooth Scroll is calculating the offset too soon, perhaps. Can you point me to a reduced test case so I can see it in action?

**Comment by strarsis** [comment]
@cferdinandi: I was able to reduce the page enough for a test case, see this pen: https://codepen.io/strarsis/pen/Wmzgdm

**Comment by cferdinandi** [comment]
Looking now. Just an FYI, Smooth Scroll offers a CDN: https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll/dist/

**Comment by cferdinandi** [comment]
Ok, so, the issue here is your use of `position: sticky` instead of `position: fixed`. It's treated as a relatively positioned element at various times and messes up the calculations smooth scroll does.

> A stickily positioned element is an element whose computed position value is sticky. It's treated as relatively positioned until its containing block crosses a specified threshold (such as setting top to value other than auto) within its flow root (or the container it scrolls within), at which point it is treated as "stuck" until meeting the opposite edge of its containing block.

**Source:** https://developer.mozilla.org/en-US/docs/Web/CSS/position

Switched to `position: fixed` addresses the issue: https://codepen.io/cferdinandi/pen/qvoQWg

**Comment by strarsis** [comment]
@cferdinandi: In this reduced test case this is not so much apparent, but I need the `sticky` behaviour.
Is there an option in `smooth-scroll` for ignoring elements for the offet calculations?

Can I use `smooth-scroll` as polyfill for [scroll-behavior](https://caniuse.com/css-scroll-behavior)?

**Comment by cferdinandi** [comment]
You might consider using the `offset` option instead of `header` to manually calculate the offset. [My gumshoe plugin has a better example of how that might work.](https://github.com/cferdinandi/gumshoe#accounting-for-fixed-headers)

```js
// Get the header
var header = document.querySelector('#my-header');

// Initialize Smooth Scroll
var scroll = new SmoothScroll('[href*="#"]', {
	offset: function () {
		return header.getBoundingClientRect().height;
	}
});
```

**Comment by strarsis** [comment]
@cferdinandi: So the header top offset is added to the overall offset and because 
the header scrolls with the page and is somehow in the flow (`position: sticky`),
the header top offset changes all the time, resulting in the incorrect scroll offsets?
Then the offset handler has to substract the top offset of the header that follows when scrolling?

**Comment by cferdinandi** [comment]
That’s accurate

**Comment by strarsis** [comment]
@cferdinandi: Using the negative `offsetTop` of header element as offset (in offset handler) fixes the issue:
```js
const headerSelector = '.nav-primary',
      headerElement  = document.querySelector(headerSelector);

new SmoothScroll('a:not([data-tab])[href*="#"]', {
  header: headerSelector,
  offset: function() {
    return -(headerElement.offsetTop);
  },
});
````

It may make sense to add a check to `smooth-scroll` for `position: sticky;` on the header element and 
then using an offset function returning the negative `offsetTop` of the header element as default option.
