### ISSUE TITLE
No options parameter for init(...)

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/smooth-scroll#464]
Currently `init(...)` only expects the header (selector string), but not the options as the constructor does.
Invoking `init(...)` results in `smooth-scroll` not using the options previously passed to constructor.

Additional proposal: It could make sense to also allow an element for the header element because sometimes it has been already looked up.

**Comment by cferdinandi** [comment]
The opposite, actually. `init()` accepts options but not a selector, as the selector is tied to the instantiation step. New selector means new instantiation.

see https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll/smooth-scroll.js#L584-L604

The only time you would need to call `init()` is to re-initialize Smooth Scroll with a fresh set of options. The behavior you're describing is exactly as intended.
