### ISSUE TITLE
Feature Request: Add `reducedMotionSupport` back.

### ISSUE THREAD

**Issue by wes-r** [cferdinandi/smooth-scroll#468]
https://github.com/cferdinandi/smooth-scroll/pull/365 made it hardcoded behavior to respect the reduce-motion setting. This is definitely an opinionated call and I'd prefer to have the scroll animation even if users have reduce-motion. I personally use my iPhone with reduce-motion as the normal phone animations are too much, however, the website scroll is nice. Therefor I'd like to still have it.

Can you please add back the `reducedMotionSupport` parameter to make this optional?

Thank you (and this library is fantastic!).

For now, I'm working around the setting by hacking the `matchMedia` function:
```js
  var matchMedia = window.matchMedia;
  window.matchMedia = function(media) {
    return media === '(prefers-reduced-motion)' ? false : matchMedia(media);
  }
```

**Comment by cferdinandi** [comment]
Definitely not. Your preferences as a developer should not trump a user’s decisions - particularly for accessibility related issues. 

Scrolling like this can be very disorienting for people with disabilities like motion sickness or certain cognitive impairments. 

This is not an “opinionated” call. It’s being ethical, caring about accessibility, and respecting the people who use what you build.

**Comment by wes-r** [comment]
It’s not my preference as a developer. It is my preference as a user.

My partner gets motion sick very easily and this type of scrolling animation does not trigger it. I actually feel the harsh direct jump can be more disorienting!

The setting is “reduce motion” and not “disable motion”.  This creates a gray area in terms of implementation. There are plenty of animations still enabled in iOS. Manually scrolling a page or clicking at the top of an iPhone to auto scroll to the top has an animation to it . The animation in this script is very similar to these animations that are still enabled by the good people of Apple.

It’s your lib, but I am a user expressing my opinion and preference. Feel free to “wonttix” but at the very least you should add a note in the “browser compatibility” section about why this won’t work for some users.

**Comment by cferdinandi** [comment]
> It’s not my preference as a developer. It is my preference as a user.

That's fair, but... adding a setting to Smooth Scroll for this doesn't give any control to *users* of your site. It's still putting the power of that decision in your hands. 

Accessibility expert recommendations around this behavior are to disable it if *Reduce Motion* it `true`. Someone may still not mind that animated scrolling, or even prefer it (I agree, the jump is jarring), but in absence of finer grained control over what is and isn't ok in terms of motion, we default to "less is better."

> There are plenty of animations still enabled in iOS.

Apple is one of the best when it comes to providing an accessible experience, but they're not infallible or perfect. No one is.

"Apple does something" isn't a compelling reason, in my opinion, to ignore guidelines from accessibility experts.

> at the very least you should add a note in the “browser compatibility” section about why this won’t work for some users.

Agreed. This was more obvious in previous iterations of the readme, and I'm not sure why I pulled it out.

**Comment by wes-r** [comment]
I haven't found any details on this case specifically. https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions.html talks about parallax  animations which I agree should absolutely be disabled. It also mentions scrolling is OK and is in control of the user. The user clicks a button and gets the scroll. This to me is the same as user clicking top of phone and triggering the scroll to the top animation.

All I'm asking for is to make the disabling of this optional. But anyway, it's a simple hack to work around this as I posted above.

**Comment by cferdinandi** [comment]
Your "hack" above breaks `Reduce Motion` across your site. Maybe you're not using it elsewhere and none of your plugins are, in which case, that's fine, but... 

Also, A11Y expert Heather Migliorisi says [disable smooth scrolling on `Reduce Motion`](https://css-tricks.com/smooth-scrolling-accessibility/), so... I do.

I feel obligated to stop developers from making decisions that are detrimental to their users or break accessibility.

**Comment by wes-r** [comment]
> Some people can literally get sick from the fast movement on the screen. I'd recommend a slow speed of the motion because if the user is going to jump across a lot of content, it can cause a dizzying effect if it's too fast.
Also, it's not a bad idea to offer users a way to turn off animations. Fortunately, Safari 10.1 introduced the Reduced Motion Media Query which provides developers a method to include animation in a way that can be disabled at the browser level.

So another option would be to keep the animation but slow it down. Again an opinion call. There is no hard rule here or hard guidance I can find.

> I feel obligated to stop developers from making decisions that are detrimental to their users or break accessibility.

You can't stop us :)! And this is mostly the only animation I have so I'm not concerned about my hack.

Alright I said my peace, thanks again for the great library, it is working beautifully for me!
