### ISSUE TITLE
ignore shift+click

### ISSUE THREAD

**Issue by danielnixon** [cferdinandi/smooth-scroll#470]
https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll/smooth-scroll.js#L498 already ignores middle-click, ctrl+click and cmd+click but it doesn't ignore shift+click (open in new window). Is this deliberate?

If not deliberate please also ignore shift+click.

**Test case:** https://codepen.io/cferdinandi/pen/wQzrdM

**Comment by cferdinandi** [comment]
Good catch! Fixed with v16.0.1: https://github.com/cferdinandi/smooth-scroll/releases/tag/v16.0.1
