### ISSUE TITLE
Bump-back when i click after another click

### ISSUE THREAD

**Issue by 8lall0** [cferdinandi/smooth-scroll#475]
If i click for the first time on a link that scrolls, it works fine.
If there is another link that scrolls to the same position, it kinda does a sort of bump-back.

Removing library works, but of course it doesn't scroll.

Am i missing something? Thanks!

**Comment by cferdinandi** [comment]
Reduced test case please

**Comment by 8lall0** [comment]
https://landing.offerteperte.net/aliprestito/fino-a-75k-euro-tassi-fissi/

**Comment by 8lall0** [comment]
I can't post code right now, but i found that it was something caused by having a sticky header.
After reading issue [#69](https://github.com/cferdinandi/smooth-scroll/issues/69) i came up with this workaround:
`offset: document.querySelector('[data-scroll-header]').clientHeight || 50`

**Comment by cferdinandi** [comment]
Ah, gotcha. I need to update the readme... Leaving this open until then.
