### ISSUE TITLE
Hash #top in url and ignoring history updating

### ISSUE THREAD

**Issue by leonid-ilin** [cferdinandi/smooth-scroll#477]
Hello! So my suggestions:

1) Possibility for "go to top" button which excluding from browser history urls like "mysite.com/#top" or "mysite.com/#" . I can realize it with initialization of two instances like (example):
```javascript
var scroll = new SmoothScroll('a[href*="#"]', {
  ignore: 'a[href="#"]'
});

var scroll2 = new SmoothScroll('a[href="#"]', {
  updateURL: false
});
```
But possibility for ignoring history updating for custom selectors with option like: ```options.ignoreUpdateUrl``` will be helpful.

2) Also i see what "#top" is hardcoded name [here](https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll/smooth-scroll.js#L311). Possibility for customization this name with options like: ```options.emptyHashSelector``` also will be useful

**Comment by cferdinandi** [comment]
Hi there, I'm deprecating this plugin and recommending everyone switch over to a now well supported CSS-native approach: https://gomakethings.com/how-to-animate-scrolling-to-anchor-links-with-one-line-of-css/
