### ISSUE TITLE
if an element is inside multiple nested scrollable elements, does it scroll each of them?

### ISSUE THREAD

**Issue by jedwards1211** [cferdinandi/smooth-scroll#478]
I've been tempted to make a library that you just pass a DOM element and it will scroll any ancestor elements as necessary to bring the requested element into view...just wanted to check if this library already does this?

**Comment by cferdinandi** [comment]
I don’t think so, but you should be able to test it pretty easily.  There’s also a native CSS way to handle this if you check the documentation

**Comment by jedwards1211** [comment]
actually I had totally forgotten, a long time ago I implemented my own fork of a lib to do this:https://github.com/jedwards1211/smoothScroll/blob/fullauto/smoothscroll.js#L111
