### ISSUE TITLE
Header option does not work on devices with Reduce motion enabled

### ISSUE THREAD

**Issue by merovinqian** [cferdinandi/smooth-scroll#479]
Header option works well when Reduce motion is disabled, but when enabled, seems like the script does not only bypass smooth scroll but even the header option.

**Comment by cferdinandi** [comment]
Yes, that's correct. The script completely bails when reduce motion is disabled.

**Comment by cferdinandi** [comment]
Thinking about this more, I can see the use case here: You'd still like to keep the content below the fixed header, but with perhaps a hard jump instead of an animated scroll?

**Comment by merovinqian** [comment]
Exactly. I would have to creatine a workaround for Reduced motion devices only. Also most dev probably don't know about this option so it could create issues with fixed elements on some devices. It Should only turn off the animated motion feature.

**Comment by cferdinandi** [comment]
Fixed with https://github.com/cferdinandi/smooth-scroll/releases/tag/v16.1.0
