### ISSUE TITLE
No smooth scroll

### ISSUE THREAD

**Issue by Mexikaner9** [cferdinandi/smooth-scroll#483]
There is no smooth scroll in my demo 
http://nirvana.bplaced.net/smooth-scroll-master/ 
it directly jumps to the anchor without transition.
whats wrong?

**Comment by cferdinandi** [comment]
Probably this: https://github.com/cferdinandi/smooth-scroll/issues/392

**Comment by Mexikaner9** [comment]
I use Google Chrome

**Comment by cferdinandi** [comment]
Which also now supports this query.

**Comment by Mexikaner9** [comment]
I'm sorry, but I don't understand what you mean.
	
I've told eight of my friends to test your smooth scroll  demo and everyone told me there is no smooth scroll !
They use Google Chrome and Mozilla Firefox.
Why does the smooth scroll not work in a modern browser with the default settings?
	
I like your script very much, but smooth scrolling should work in any browser without any additional settings in the browser.

**Comment by cferdinandi** [comment]
Then all 8 of your friends have their operating systems set to reduce motion.

This is an operating system (not browser) setting that indicates you do NOT want motion when it is optional. This is used by people who get motion sick or find rapid movement disorienting.

Your demo works fine for me, because I have this setting turned off.

The script behaves this way because to do otherwise would be to ignore user preferences and would make it inaccessible.

You can learn more about how to enable/disable this setting here: http://osxdaily.com/2018/12/17/how-reduce-motion-mac-disable-animations/

**Comment by Mexikaner9** [comment]
Thank you for your detailed answer!

**Comment by Mexikaner9** [comment]
Hello again.
My friends and I use Windows.
We also tested your demo on our mobile phone (Samsung Galaxy) and also there is no smooth scroll

**Comment by cferdinandi** [comment]
What OS version and browser?

**Comment by Mexikaner9** [comment]
Windows 7: Google Chrome and Mozilla Firefox
Windows 8: Google Chrome 
Windows 10: Google Chrome and Mozilla Firefox
Android: Google Chrome

**Comment by cferdinandi** [comment]
I've done some additional testing on other OS/browser combinations, and everything is working the way I'd expect. The only thing I can say is that you must have a setting enabled on your machines/devices to disable animations. The script checks for that setting, and if the browser say it's enabled, does *not* animate.

Chrome and Firefox both support that feature. IE does not.

**Comment by Mexikaner9** [comment]
Hello,
I have tested your and my example on other computers. In total over 20 computers.
On no computer, no matter which browser, smooth-scroll works.
And nobody's enabled the setting to disable animations.
I have used your smooth-scroll in a project some years ago and people liked your smooth-scroll script.
Can you provide also a version of smooth-scroll without the Check if the setting to disable animations is enabled or not so smooth-scroll always works? That would be great!

**Comment by Mexikaner9** [comment]
I'm sorry, but I didn't mean to say there was a mistake.
You wrote:
I've done some additional testing on other OS/browser combinations, and everything is working the way I'd expect.

I just wanted you to ask if you can provide also a version of smooth-scroll without the Check if the setting to disable animations is enabled or not so smooth-scroll always works.

**Comment by cferdinandi** [comment]
Here's where it happens: https://github.com/cferdinandi/smooth-scroll/blob/master/dist/smooth-scroll.polyfills.js#L163 If you set that to always return `false` it will disable the feature.

I gave this some more thought, and in browsers without support for `matchMedia()` or `prefers-reduce-motion`, I think disabling the animation is still the right call. I'd prefer to err on the side of increased accessibility, even if it means decreasing functionality.

**Comment by Mexikaner9** [comment]
Thanks for your help!
Can you please tell me where I can disable the feature in smooth-scroll.polyfills.min.js ?
Thanks in advance!

**Comment by cferdinandi** [comment]
I cannot. Minified code isn't really meant to be read by humans. You could update the unminified version and minify it yourself, but for testing, it should be fine as-is.

**Comment by Mexikaner9** [comment]
thank you !
