### ISSUE TITLE
The Scroll crosses the the mark and goes bit ahead

### ISSUE THREAD

**Issue by cinghaman** [cferdinandi/smooth-scroll#484]
I have a smooth scroll set on menu links to scroll to sections on the page, every section has a title which has the id example <h1 id="contact">Contact </h1>
and followed by the content of the section, when someone clicks on contact link it scrolls to correct section but almost stops at the mid of content instead of stopping at the top of the title
This is where it stops instead of the actual title https://prnt.sc/owpy5k

Just wanted to add I have fixed header if I remove fixed header it works fine

**Comment by cferdinandi** [comment]
are you adding an offset for the fixed header at all?

**Comment by cinghaman** [comment]
I am just adding class sticky with property: position: fixed;

**Comment by cferdinandi** [comment]
https://github.com/cferdinandi/smooth-scroll#fixed-headers
