### ISSUE TITLE
Hello, I just replaced html and css in your demo, and it doesn't work for some reason. It might be duo to scroll in container?

### ISSUE THREAD

**Issue by artyor** [cferdinandi/smooth-scroll#487]
https://codepen.io/artyor/pen/YzzEQgg Here is my demo.

I guess I need to apply it differently because this is not for main scrollbar?

**Comment by cferdinandi** [comment]
It doesn't work with secondary content like that. It can only scroll the `body`. You might want to take a look at the CSS property for this: https://gomakethings.com/smooth-scrolling-links-with-only-css/

**Comment by artyor** [comment]
Using that as 2nd solution, but wanted to have it working on every browser. Thanks anyway!
