### ISSUE TITLE
Smooth-Scroll is not working for me.....

### ISSUE THREAD

**Issue by castana1962** [cferdinandi/smooth-scroll#488]
Hi cferdinandi,
Sorry to bother you but I am new in this topic and trying this Scroll 
Effect
I added it to my simple website and this effect is not working for me.....
Could you help me to fix it?
Thanks for your time
Alejandro

**Test case:** https://codepen.io/cferdinandi/pen/RqGLpz

**Comment by cferdinandi** [comment]
Please open a new issue with a reduced test case. Also, check if you have Reduced Motion enabled in your browser/OS, as Smooth Scroll will not run in that case.

**Comment by castana1962** [comment]
Hi again
Sorry for my ignaorance but Could you advice me abouy how to open a new issue with a reduced test case in Github?
Thanks

**Comment by cferdinandi** [comment]
No worries. Details here: https://github.com/cferdinandi/smooth-scroll/blob/master/.github/contributing.md
