### ISSUE TITLE
doesnt scroll up from the bottom

### ISSUE THREAD

**Issue by ArneBroedel** [cferdinandi/smooth-scroll#49]
Hi, 
thanks very much for this project. It was looking great immediately. But I have a problem.
When I scroll down to the absolute bottom of my page there is a fault behavior. When I click any link there (links to a different position on the same site) there is just a little jump upwards approximately a pixel or so. If I hit the link about 15 times it goes up 1 pixel but then suddenly on the 16th time it scrolls smoothly to the right position.
If I first scroll up a little manually it works on the first click. I couldn't figure out what the problem is. Any advice?

**Comment by dennisperremans** [comment]
Thank you! This solved it for me.
I've changed easing: 'easeInOutCubic' to easing: 'easeOut'.

**Comment by cferdinandi** [comment]
@dennisperremans Sorry you had to update your easing method. I'm wondering if there's a weird rounding issue happening or something..

**Comment by goodguyry** [comment]
Thanks @cferdinandi and @JonasHavers for the details. I thought I was losing my mind. The `easeOut*` fix worked for me, too. Thanks again!

**Comment by bastardesigns** [comment]
`/**
 * Stop the scroll animation when it reaches its target (or the bottom/top of page)
* @private
		 * @param {Number} position Current position on the page
		 * @param {Number} endLocation Scroll to location
		 * @param {Number} animationInterval How much to scroll on this loop
		 */
		
		var stopAnimateScroll = function (position, endLocation, animationInterval) {
			var currentLocation = root.pageYOffset;
			 console.log(root.innerHeight + currentLocation);
			 console.log("espacio "+ documentHeight);
			if ( position == endLocation || currentLocation == endLocation || ( (root.innerHeight + currentLocation) >= documentHeight ) ) {
				clearInterval(animationInterval);
				if ( !isNum ) {
					anchorElem.focus();
				}
				animateSettings.callback( anchor, toggle ); // Run callbacks after animation complete
			}
		};`

**Comment by bastardesigns** [comment]
![image](https://cloud.githubusercontent.com/assets/18714150/14877001/de3580fa-0cef-11e6-9857-904412f50348.png)

@cferdinandi, Sorry for my english, but I Solve the problem of displacement stop at the bottom deleting de "|| ( (root.innerHeight + currentLocation) >= documentHeight )" of the picture that I attached.  <Line 381>. 
If the problem was solved , sorry to bother . I am newbie.

**Comment by bastardesigns** [comment]
@cferdinandi check deleting the line selected in the img. I can fix the problem of stoping scroll at the bottom.
![image](https://cloud.githubusercontent.com/assets/18714150/14877300/3a86ac06-0cf2-11e6-928c-9fd7466a9e52.png)

**Comment by cferdinandi** [comment]
@bastardesigns That line is needed to prevent an infinite loop from happening if the scroll target is outside of the window.
