### ISSUE TITLE
not working on Firefox 70.0.1 / Ubuntu

### ISSUE THREAD

**Issue by a4bits** [cferdinandi/smooth-scroll#490]
Hello,

I am using Firefox 70.0.1 on Ubuntu,
Seems like scrolling on demo and on my site are not working.
It is not smoothly scrolling but jumping instantly. 

Thank you,
Arek

**Comment by cferdinandi** [comment]
This is almost certainly because the browser/OS combo is telling Smooth Scroll to reduce motion. How to address this varies, and some combinations always send that query as true.

**Comment by a4bits** [comment]
IMO good to put it onto known issues. There are some scroll npm scripts that work normally on this browser/os. I had issue with smooth-scroll :-/

**Comment by cferdinandi** [comment]
https://github.com/cferdinandi/smooth-scroll#reduce-motion-settings

**Comment by a4bits** [comment]
ah, true :-) missed it somehow -- was concentrating on keywords 'not working' 

-- there are setting in system to save energy and cancel unnecessary movement, it was it, disabled it and it works. good idea about using this feature in your script.
