### ISSUE TITLE
Does not support special characters (ä,ö,å, etc.)

### ISSUE THREAD

**Issue by Nastradoomus** [cferdinandi/smooth-scroll#492]
This is not a problem but it's worth to mention. Had an ID called myymälä. Smoothscroll didn't react to it as it should.

**Comment by cferdinandi** [comment]
Hey, so sorry about this. This was a bug that had been fixed many versions ago but got reintroduced in a rewrite. v16.1.1 fixes it. Just pushed.

Thanks for letting me know!
