### ISSUE TITLE
[Question] Draggable scrolling?

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/smooth-scroll#493]
Is it possible to make the whole scroll area draggable by mouse (not just by using a touch input)?
This can be very helpful in some cases, where it is also very unlikely that the text is selected for being copied anyway.

**Comment by cferdinandi** [comment]
Is this posted on the right project? I'm not sure what you mean if it is.

**Comment by strarsis** [comment]
Indeed, this is the wrong repository.

**Comment by cferdinandi** [comment]
Phew! Good luck!
