### ISSUE TITLE
Custom selector, Events and RaF

### ISSUE THREAD

**Issue by davidhund** [cferdinandi/smooth-scroll#5]
Thanks for the script. Nice and simple (loving vanilla js).

A couple of thoughts:
- Would there be any benefit in using `requestanimationframe` over `setInterval`?
- It would be awesome to set a personal selector for `scrollToggle` instead of using the convention of `.scroll`. This would allow us to use e.g. `nav a` instead of adding a classname to all our links
- Since the script prevents the link's default event (such as changing the `location.hash`) it's harder to e.g. set an `.is-active` class to highlight the 'current section'. If the script could set a classname to the currently active link that would be great

I know I should probably just do this and issue a PR but just wondering what you think (first) :-)

**Comment by cferdinandi** [comment]
So it's almost 2 years later, but there's now a selector variable in the `options`.

**Comment by davidhund** [comment]
Ghehe nice, thanks! :ok_hand:
