### ISSUE TITLE
v16.1.1: Not published on npm!

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/smooth-scroll#501]
The [latest release on this GitHub repository](https://github.com/cferdinandi/smooth-scroll/releases) of `smooth-scroll` is `v16.1.1`, 
but [on npm](https://www.npmjs.com/package/smooth-scroll) only release `v16.1.0` is published.

Please publish `smooth-scroll` release `v16.1.1` also on npm.

**Comment by cferdinandi** [comment]
Fixed, thanks
