### ISSUE TITLE
Scroll without #id_name on url

### ISSUE THREAD

**Issue by rajuahammadfans** [cferdinandi/smooth-scroll#504]
Hi, first thanks for this awesome project.

I used on my project everything is fine but has a small problem. I want to scroll without #id_name on the URL.
**Screenshots:** http://prntscr.com/ri9b7v

I included file from "dist/smooth-scroll.min.js" and activation code is:
`let scroll = new SmoothScroll('.nav a[href*="#"]');`

Thanks again

**Comment by cferdinandi** [comment]
You want to set the `updateURL` option to `false`: https://github.com/cferdinandi/smooth-scroll#options-and-settings
