### ISSUE TITLE
Focus is not adjusted when reduceMotion is enabled

### ISSUE THREAD

**Issue by guanpu** [cferdinandi/smooth-scroll#505]
System settings:
in Mac: go to System Preference -> Accessibility -> Check "reduce motion"
in Windows: goto Control Panel -> System & Security -> Advanced system settings -> Performance settings -> uncheck "Animate controls and elements inside windows"
**Test case:** 
https://codepen.io/puguan/pen/qBdJbWK

As in the above case, it's working fine if you allow animation in your OS settings. But if you turn on reduce motion either in mac or windows, after you click link2, then tab again, it will focus on link3 (instead of focusing on the next focusable of the target of link2). The animation preference should not affect the tab order.

**Comment by cferdinandi** [comment]
Unable to replicate. The script bails before ever running if reduce motion is enabled and falls back to the default browser behavior, so this shouldn't be happening.

I wonder if some other setting in your browser is causing this.

**Comment by guanpu** [comment]
Yes, you're right it can't be replicated directly from the codepen sample, sorry I didn't very that before posting, maybe it's because of codepen's preview mechanism. But if concatenate the code from codepen into a single html file, (alternatively you can rename below file to be an HTML file) and open in a browser(in my case Chrome 80) with the OS reduceMotion feature on, it will replicate.

[index.txt](https://github.com/cferdinandi/smooth-scroll/files/4373343/index.txt)

**Comment by cferdinandi** [comment]
PR merged. Thanks!
