### ISSUE TITLE
Edge case issue - Failed to execute 'pushState' on 'History when linking to a from that has an input with name 'id'

### ISSUE THREAD

**Issue by Mistermelotte** [cferdinandi/smooth-scroll#509]
When te target for a smoothscroll link is a form, and that form contains an input with name id following error  is thrown
`Uncaught DOMException: Failed to execute 'pushState' on 'History': HTMLInputElement object could not be cloned.`

**Test case:** https://codepen.io/mistermelotte/pen/bGdONNJ

**Possible Solution**
Replace `anchor.id` in the updateUrl function with `anchor.getAttribute('id')'`

**Comment by cferdinandi** [comment]
Hi there, I'm deprecating this plugin and recommending everyone switch over to a now well supported CSS-native approach: https://gomakethings.com/how-to-animate-scrolling-to-anchor-links-with-one-line-of-css/
