### ISSUE TITLE
overflow-y: scroll  in css breaks smooth-scroll

### ISSUE THREAD

**Issue by mrosentr** [cferdinandi/smooth-scroll#510]
Hi, 
I notice when using the overflow-y: scroll it breaks functionality in smooth-scroll.
See my reduced test case:

**Test case:** https://codepen.io/mrosentr/pen/GRJzJoV

Check this case to see it working as expected using native css without smooth-scroll.  However, this does not work in IE 11 hence the need for smooth-scroll:

Example Case:  https://codepen.io/mrosentr/pen/rNVoymj

Thanks, 
mrosentr

**Comment by cferdinandi** [comment]
Sadly, certain bits of math that the plugin does break with certain CSS combinations.

Today, I generally recommend people skip this plugin and use the CSS `scroll-behavior: smooth` property instead.

**Comment by mrosentr** [comment]
Unfortunately scroll-behavior: smooth doesn't work in IE 11 and such a library is needed.  Is this code base not maintained anymore?

**Comment by cferdinandi** [comment]
It is, but this falls under "known edge case that won't be addressed."

The math is hard, and making it work in all use cases is harder. I'm happy to treat this behavior as a progressive enhancement. I know that might not be the case for you for specific clients, but that's the line I've drawn on maintenance. Sorry! 😔
