### ISSUE TITLE
Disable focus on options

### ISSUE THREAD

**Issue by giray123** [cferdinandi/smooth-scroll#511]
I use this beautiful library for scrolling lyrics of a song (not with a click but programmatically scrolling). However every time a scroll ends it steals the focus if I try to type in a text or textarea element. I wish to disable this feature, but I could not find any options. 
(Thank you for the great library)

[Codepen Link](https://codepen.io/giray123/pen/eYNaYrr)

**Comment by cferdinandi** [comment]
Hey, this feels like an edge case outside the intended purpose of Smooth Scroll.

It's not _stealing_ focus so-much-as shifting it onto the element that's been scrolled to, which is an important accessibility behavior.

You should absolutely feel free to fork and modify for what you're trying to do, though.
