### ISSUE TITLE
Back button with header issue

### ISSUE THREAD

**Issue by leonetti** [cferdinandi/smooth-scroll#512]
I found this error while using Gatsby.js

Gatsby uses Link's that prefetch resources... https://www.gatsbyjs.org/docs/gatsby-link/

I've noticed when having a header option in the settings the page breaks after clicking the back button. Works fine without the header setting, can't reproduce issue in codepen 

The behavior:
Page works fine until a smoothScroll link is clicked and the page jumps to the top and cannot scroll down

**Comment by cferdinandi** [comment]
Hi there, I'm deprecating this plugin and recommending everyone switch over to a now well supported CSS-native approach: https://gomakethings.com/how-to-animate-scrolling-to-anchor-links-with-one-line-of-css/
