### ISSUE TITLE
Missing support to mouse wheel and touch events to 'smooth-scroll' the page

### ISSUE THREAD

**Issue by migueleliasweb** [cferdinandi/smooth-scroll#78]
I forked the repo and addded mouse wheel and touch events support.

I'm finishing updating the readme and other fixes to make a pull request.

@cferdinandi , if you can, have a look and tell me what you think.

The forked repo: https://github.com/migueleliasweb/smooth-scroll

**Comment by LouisaNikita** [comment]
@migueleliasweb hello,i tried this lib  (url[https://github.com/migueleliasweb/smooth-scroll]) and there is something wrong "Cannot read property 'addEventListener' of undefined". when i use the lib of  cferdinandi ,they can read this property. can u tell me wat happened ? or y ?
