### ISSUE TITLE
"Overflow-x: hidden" in CSS breaks smooth scroll

### ISSUE THREAD

**Issue by samusgray** [cferdinandi/smooth-scroll#8]
Hi there, 

Are you aware of a way for this to work with overflow-x: hidden set on the html and body elements? Any idea why this breaks the functionality? I'm looking into it now, but thought you may already have a solution. :)

Thanks!

**Comment by mingraham** [comment]
I had overflow-x:hidden in my CSS for both html and body. I split up my CSS so that overflow-x:hidden was only affecting body, and not html. After that, it did not matter whether the jQuery used $('*') or $('html,body'). Hope this helps!

**Comment by veganista** [comment]
I have ran across this problem and have created a [fiddle](https://jsfiddle.net/veganista/29rmt32x/).

I'm not sure if this is directly related to your plugin as i have distilled it down to this [fiddle](https://jsfiddle.net/veganista/g98zcwes) and it still seems to happen.

**Comment by Barrytron** [comment]
@mingraham thanks you saved me!
