### ISSUE TITLE
Add `selector` as option for `init()`

### ISSUE THREAD

**Issue by vlucas** [cferdinandi/smooth-scroll#99]
I am creating a mobile app that requires _all_ local anchor links to smoothly scroll to their target destination. I would like the ability to provide a custom CSS selector instead of having to add a `data-scroll` attribute to each of my links. The selector for all local links is: `a[href^='#']`.

**Comment by cferdinandi** [comment]
So it's almost a year later, but there's now a selector variable in the `options`.

**Comment by shofer4eto** [comment]
Hi there,

How do I add multiple selectors? Thanks!

**Comment by cferdinandi** [comment]
@shofer4eto as a comma-separated list. Example:

```js
var scroll = new SmoothScroll('.js-scroll, [data-scroll]');
```

**Comment by shofer4eto** [comment]
smoothScroll.init({
		selector: '[rel="smooth_scroll"],[rel="gumshoe_scroll"]',
...............


Doesn't work for me...

**Comment by cferdinandi** [comment]
Please provide a reduced test case per the support Docs. https://github.com/cferdinandi/smooth-scroll/blob/master/SUPPORT.md

**Comment by shofer4eto** [comment]
Hi again,

I am using SmoothScroll + Gumshoe together.
Trying to initialize smoothscroll like so:

```
smoothScroll.init({
		selector: '[rel="smooth_scroll"],[rel="gumshoe_scroll"]', 
		speed: 600,
		updateURL: false,
		offset: 0,
});
```

as my gumshoe items are described separately than the regular smoothscroll links (with a rel = gumshoe_scroll).

```
gumshoe.init({
	selector: 'a[rel="gumshoe_scroll"]',
	offset: 0, // Distance in pixels to offset calculations
	activeClass: 'is-selected', // Class to apply to active navigation link and it's parent list item
});
```

My next question is how can I possible run gumshoe for 2 separate navigations? I setup a nice side Dotted navigation running on Gumshoe and it works fine, but I want a regular top header fixed navigation working along with the side dotted navigation and I want both menus spying on the location and activating their ACTIVE classes. Thanks in advance! :)

**Comment by cferdinandi** [comment]
Per the Docs and my guidance above, you're not initializing smooth scroll correctly. Also, at the moment gumshoe only works on one menu.
